### ISSUE TITLE
Remove warning that unprocessed packages were found from NuGetPackageVerifier

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#104]
We landed on not requiring listing individual packages to be listed in NuGetPackageVerifier.json. However the executable continues to print a warning for packages that aren't present:

```
Found 2 unprocessed packages. Every package in the repo should be listed in exactly one package set. Running default or all rules on unlisted packages.
```

Presumably unlisted packages should no longer be treated as a warning.

**Comment by Eilon** [comment]
@ajaybhargavb is this still a problem?

**Comment by pranavkm** [comment]
Yes! Fixing this would be nice so that we get to a place where we don't have to list proejcts in individual project's NuGetPackageVerifier.json

**Comment by ajaybhargavb** [comment]
Yes @Eilon and I discussed mass editing all `NuGetPackageVerifier.json` files to remove all package listings and just have the rule list. Maybe we should do that with this.

**Comment by Eilon** [comment]
@ajaybhargavb yeah we should do that. I didn't realize we hadn't yet done it 😄

**Comment by ajaybhargavb** [comment]
Keeping this open until I update all NPV.json files.

**Comment by ajaybhargavb** [comment]
All repos updated.
