### ISSUE TITLE
Need to enable package metadata rule in all repos

### ISSUE THREAD

**Issue by Eilon** [aspnet/BuildTools#11]

**Comment by Eilon** [comment]
Depends on https://github.com/aspnet/DnxTools/issues/26.

**Comment by Eilon** [comment]
Moving to RTM because it's unlikely we'll get every shipping package to have all suggested metadata for RC2 (though we'll be super close).

**Comment by Eilon** [comment]
@ajaybhargavb do you think this is something we can do in the near future? Is it blocked on anything else?

**Comment by ajaybhargavb** [comment]
The rule checks for Summary, Title and Tags https://github.com/aspnet/BuildTools/blob/dev/src/NuGetPackageVerifier/Rules/RequiredPackageMetadataRule.cs#L12. I know we have tags set in `project.json`. Are we setting Summary and Title somewhere?

**Comment by Eilon** [comment]
I don't think we use summary (we use description instead) and we don't use title (we use id instead).

Can we change and enable the rule for just the metadata we actually use?

**Comment by ajaybhargavb** [comment]
4dc92c7efad058d347020112f75f24831f3d0bc8
