### ISSUE TITLE
Add a --quiet option to disable logging info messages in NuGetPackageVerifier

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#116]
Currently there is no support to hide Info log messages. It would be better to have the verifier just log messages for errors and warnings as part of the build.

**Comment by Eilon** [comment]
Which tool is this about?

**Comment by Eilon** [comment]
Assuming it's NuGetPackageVerifier, please go ahead and add it. And update the bug title 😄
