### ISSUE TITLE
Support netcoreapp1.1 tfm

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#121]
The dependency graph of apps targeting netcoreapp1.1 will be slightly different from those using netcoreapp1.0. Build tools should account for this new TFM.

I found two instances where this might apply, and we should investigate if netcoreapp1.1 makes a difference:
SplitPackages only check compatibility with netcoreapp1.0.
DependencyPackager only crossgen's for netcoreapp1.0.

**Comment by natemcmaster** [comment]
+ netcoreapp1.2  cref https://github.com/NuGet/Home/issues/3576

**Comment by natemcmaster** [comment]
I'm not sure how relevant "netcoreapp1.1" is anymore, but there may be related work for .NET Core 2.0. 

@Eilon do we expected ASP.NET Core 2.0 packages to be compatible with the netcoreapp1.0 TFM? i.e. we are keeping netstandard1.3 where possible. Will packages that upgrade to netstandard2.0 be required to keep a TFM that is compatible with netcoreapp1.0?

cc @DamianEdwards

**Comment by Eilon** [comment]
Actually, can you remind me what this bug is about? Is it about our build tools run on, about what the tools work with and/or produce, or something else?

**Comment by natemcmaster** [comment]
The bug was that package cache generation uses .NET Core 1.0, but the dependency graph for .NET Core 1.1 is different, so cross gen uses the wrong references.

Also, our coherence check only ensures that packages are compatible with .NET Framework 4.5.1 or .NET Core 1.0. I know this is changing, but not sure what the new runtime version prerequisites will be.

**Comment by Eilon** [comment]
@JunTaoLuo @DamianEdwards - with the new package cache/store feature, presumably this issue doesn't apply anymore.

However, for our 2.0 wave of bits, of course the new package cache will work when running on .NET Core App 2.0, but do we expect it to work on 1.0/1.1?

**Comment by JunTaoLuo** [comment]
The package cache is built for netcoreapp2.0 and it's not expected to work on 1.0/1.1. However, we can try building the package cache for netcoreapp1.1 and 1.0.

**Comment by Eilon** [comment]
@DamianEdwards is that a thing? Do we need that?

**Comment by DamianEdwards** [comment]
I don't really understand this issue. Can we sync in person?

**Comment by JunTaoLuo** [comment]
Spoke offline, this is not a supported scenario.
