### ISSUE TITLE
DependenciesPackager should fail if crossgen fails

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#122]
When crossgen fails, DependenciesPackager only issues a warning and will still pass. It should fail so we can resolve the problem.

e.g.
```
 warn: DependenciesPackager.Program[0]
 Crossgen failed for /buildspace/artifacts/rc1-22720-dev/x64/microsoft.aspnet.webapi.client/5.2.2/lib/portable-wp8+netcore45+net45+wp81+wpa81/System.Net.Http.Formatting.dll. Exit code 33.
```

**Comment by javiercn** [comment]
We should do a couple of things. We can do https://github.com/aspnet/BuildTools/issues/96 and we can limit the things that we cross gen to the things that we are actually shipping. (Currently we crossgen everything and then filter the dlls).

The proposal is to build a response file and only crossgen the things that we actually care about in place (this will remove the need for publishing and other steps that we take).

That way, we can avoid getting false errors like the one above (We don't care about failing to crossgen microsoft.aspnet.webapi.client and some other packages like that)

**Comment by natemcmaster** [comment]
> We don't care about failing to crossgen microsoft.aspnet.webapi.client

However we solve this, there should be someway to know that this is the case. e.g. add an includsion/exclusion list.

**Comment by Eilon** [comment]
@javiercn assigning to you. We should definitely have better failure modes for this.

**Comment by javiercn** [comment]
This is done as part of 6da936c9b816fff743355db82dd3cb28e110f901
