### ISSUE TITLE
Move away from project context APIs for DependenciesPackager and ApiCheck

### ISSUE THREAD

**Issue by javiercn** [aspnet/BuildTools#127]
These are being deprecated, we should switch to using NuGet APIs directly or similar from the CLI

**Comment by natemcmaster** [comment]
Would suggest converting these tools to run as tasks, kind of like how we did with NugetPackageVerifier

**Comment by natemcmaster** [comment]
I believe this was resolved in https://github.com/aspnet/BuildTools/pull/169.
