### ISSUE TITLE
SplitPackages needs to generate xml instead of project.json

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#134]
SplitPackages current generates a project.json file. Downstream tools use this to run a restore.

We will need to update the tool to generate an xml file that uses `PackageReference`'s instead.

**Comment by Eilon** [comment]
@jbagga let's chat about this when you're back in the office.

**Comment by natemcmaster** [comment]
@jbagga as long as your at this, we can probably stop cross-compiling to tool for net451. cref https://github.com/aspnet/BuildTools/pull/138#discussion_r94819357
