### ISSUE TITLE
Disable Package Analysis on the NuGet PackTask

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#190]
A lot of our builds produce warnings as part of packing to this package analysis rule that recommends including a `Summary` when the `Description` exceeds 300 characters:

```
  \NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue found with package 'Microsoft.AspNetCore.Http.Abstractions'. [\HttpAbstractions\src\Microsoft.AspNetCore.Http.Abstractions\Microsoft.AspNetCore.Http.Abstractions.csproj]
  \NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(104,5): warning : Issue: Consider providing Summary text. [\HttpAbstractions\src\Microsoft.AspNetCore.Http.Abstractions\Microsoft.AspNetCore.Http.Abstractions.csproj]
  \NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(104,5): warning : Description: The Description text is long but the Summary text is empty. This means the Description text will be truncated in the 'Manage NuGet Packages' dialog. [\HttpAbstractions\src\Microsoft.AspNetCore.Http.Abstractions\Microsoft.AspNetCore.Http.Abstractions.csproj]
  \NuGet.Build.Tasks.Pack\buildCrossTargeting\NuGet.Build.Tasks.Pack.targets(104,5): warning : Solution: Provide a brief summary of the package in the Summary field. [\HttpAbstractions\src\Microsoft.AspNetCore.Http.Abstractions\Microsoft.AspNetCore.Http.Abstractions.csproj]
```

These show up as 4 separate warnings in the build output. Unfortunately, there doesn't seem to be *simple* way to supply a Summary to the pack task (https://github.com/NuGet/Home/issues/4737). We should disable the analysis via the Internal.SDK.

**Comment by pranavkm** [comment]
cc @Eilon \ @natemcmaster

**Comment by natemcmaster** [comment]
Could we do a length check on `Description` and set `NoPackageAnalysis=true` just for those packages that have this issue?

**Comment by pranavkm** [comment]
We could. That said, I'm not entirely sure there's a lot of value in running the analysis: https://github.com/NuGet/NuGet.Client/tree/dev/src/NuGet.Core/NuGet.Commands/Rules. A lot of it is designed for users generating it from a spec and creating packages by hand - not necessarily for the way packages are built by the SDK.

**Comment by Eilon** [comment]
I agree it seems at best marginally useful, so disabling for now is certainly fine, but it'd be nice to have it running.

**Comment by Eilon** [comment]
Do we have a bug to re-enable it?

**Comment by pranavkm** [comment]
Here you go: https://github.com/aspnet/BuildTools/issues/192
