### ISSUE TITLE
Consider adding a verifier check to ensure `AssemblyFileVersion` exists in assemblies and has a non-zero revision.

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#196]
@joeloff might know better, but I think having the revision is useful in setup scenarios (or maybe it's the opposite of useful). Either way would help to add this.

**Comment by joeloff** [comment]
Are these assemblies that are being shipped as part of an MSI? For setup, AssemblyFileVersion will only impact upgrade scenarios for MSI based installs to determine if files are old or new

**Comment by pranavkm** [comment]
It's all of the AspNetCore binaries.

**Comment by joeloff** [comment]
I see. Yeah, would be good to set it. Once we start using fallback locations for the local feeds, we'd be shipping preunzipped nupkgs and then the installers will definitely care about assembly file version information when it comes to upgrades.

**Comment by Eilon** [comment]
I think @jbagga added a check for `AssemblyFileVersion` not too long ago (and in particular, to make sure it matches the package version).

Regarding Revision, how would we ever even use it?

**Comment by pranavkm** [comment]
> I think @jbagga added a check for AssemblyFileVersion not too long ago (and in particular, to make sure it matches the package version).

It might have been the `AssemblyVersion`. The `AssemblyFileVersion` always has an auto-incrementing component (the revision number).

**Comment by jbagga** [comment]
We have a rule that checks if [`AssemblyFileVersion` exists](https://github.com/aspnet/BuildTools/blob/dev/src/NuGetPackageVerifier/Rules/AssemblyHasVersionAttributesRule.cs). The rule I added checks if the Major, Minor and Patch version numbers [match the package version](https://github.com/aspnet/BuildTools/blob/dev/src/NuGetPackageVerifier/Rules/PackageVersionMatchesAssemblyVersionRule.cs), but nothing for the revision number

**Comment by Eilon** [comment]
@joeloff it would be good to understand what the exact requirement here is. I would guess that every time WTE ingests a new set of ASP.NET/EF Core packages that they'll have a different assembly FILE version anyway because I think we put the build number in there as the revision:

![image](https://cloud.githubusercontent.com/assets/202643/24083332/5df6411a-0c92-11e7-8f6a-0aaae9566b7d.png)

So, I would guess that we're already ok, no?

**Comment by joeloff** [comment]
@Eilon Yup, that is all we need. As long as the AssemblyFileVersion attribute is set, we should be good.

**Comment by Eilon** [comment]
Ok, closing this bug then.
