### ISSUE TITLE
ApiCheck: use System.Reflection.Metadata

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#198]
We should look into using System.Reflection.Metadata for API check. It should be faster, more flexible, less fragile.

Comparison of APIs and what they requires to produce a list of type definitions:

_System.Reflection.Assembly.Load_: 

- assembly file
- project.assets.json
- plus all the packages in NuGet cache that are listed in the assets file
- framework name
- a compatible runtime. Because it loads assembly for **execution**. ApiCheck only uses the assembly for **inspection**. This means "apicheck.exe" can only inspect .NET Framework libraries, and "dotnet apicheck" can only check .NET Core and compatible .NET Standard libraries.

_System.Reflection.Metadata.MetadataReader_:
- assembly file

**Comment by natemcmaster** [comment]
cc @dougbu

**Comment by dougbu** [comment]
Yeah, that sounds similar to #207 but this issue is more narrow.

**Comment by dougbu** [comment]
@natemcmaster I think of this as one way to address #201. Do you disagree?

**Comment by natemcmaster** [comment]
Basically the same issue. In #201 you described the problems I've encountered that led me to suggest this approach.

**Comment by Eilon** [comment]
Closing for the reasons described in https://github.com/aspnet/BuildTools/issues/201.

**Comment by natemcmaster** [comment]
We should re-visit this. The tool's dependency on the .NET Core runtime creates a chicken-and-egg problem when the runtime breaks.

Example from today: the API check tool has to rev in lock-step with runtime.

 - 🐣  - Mirror build attempts to upgrade .NET Core to new version that has breaking change. API check fails because it can't run on the new runtime.
     ```
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
        File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ---> System.IO.FileNotFoundException: Could not load the specified file.
        File name: 'System.Diagnostics.DiagnosticSource'
        at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
        at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
        at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
        at System.Reflection.RuntimeMethodInfo.get_ReturnType()
        at ApiCheck.ApiListingGenerator.SameSignature(MethodInfo candidate, MethodInfo method)
    ```
 - 🐔  -  Normally, API check depends on the packages brought in from the mirror. We re-compile our tool against this versions once the mirror passes.
 - 🍳 - We can't update API check until mirror passes. Mirror can't pass until API check updates. 

(side note: it gets worse. If we maOnce we push the new version of API check, existing `dev` branch builds will fail until the mirror passes.

Ways to breaking the cycle:
 - Disable API check on mirror. (Easiest)
 - Manually rebuild and push the API check tool to use a version newer than what the mirror has approved. This breaks `dev` builds until mirror passes.
 - Keep API check enabled on mirror, but disable in `dev builds`

All of these are manual and a bit painful.

cc @ryanbrandenburg @mikeharder

**Comment by Eilon** [comment]
I think disabling API check on mirror makes sense... it doesn't ever make sense to run it there (it can't be broken there if it's already passing everywhere else).

**Comment by Eilon** [comment]
@javiercn - can you work with folks e.g. @kichalla to disable API check during the mirror?

**Comment by Eilon** [comment]
Actually I'll log a new bug for this and re-close this.

**Comment by Eilon** [comment]
Moved the current issue to https://github.com/aspnet/CoreCLR/issues/237

Closing this because we're still not planning on making the proposed changes here.
