### ISSUE TITLE
Reenable AssemblyIsBuiltInReleaseConfigurationRule

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#202]
This todo: https://github.com/aspnet/BuildTools/blob/dev/src/NuGetPackageVerifier/Rules/AssemblyIsBuiltInReleaseConfigurationRule.cs#L18. Caused by bugs in cecil.

**Comment by Eilon** [comment]
Dup of https://github.com/aspnet/BuildTools/issues/140.
