### ISSUE TITLE
Get Api Check working x-plat

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#213]
Should fix whatever blocks Api Check x-plat and revert 4f67377.

Commit 4f67377 temporarily disabled API Check unless on Windows. I did this because the tool was unable to resolve some dependencies for the FileSystem repo. That's rather early in the Universe build and likely indicates more-extensive issues. (It's possible my local package cache had a mix of cases in the folder names or that the issue was transient.)

**Comment by Eilon** [comment]
Closing because ultimately we'll find the failure either on AppVeyor or on the internal CI.
