### ISSUE TITLE
Make it easier to generate API Check baselines

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#215]
The API Check tool can generate baseline files. But, the tool must be run separately for each TFM and requires about four command-line options. And, the `ApiCheckTask` only supports comparing an assembly with its baseline and exception files, (That limitation was just for expedience.)

A separate task to generate baselines or an additional option for the `ApiCheck` task to do generation would help developers filling these gaps.

Would be nice to also add KoreBuild and even Universe targets like `AddMissingBaselines` and perhaps (for use after 2.0.0 ships) `ResetBaselines` which would overwrite existing baselines and remove exception files.

**Comment by Eilon** [comment]
The value seems low, so closing this. We only need to do this for each new major/minor release.
