### ISSUE TITLE
Check if SplitPlackages can be targeted only for .NET Core

### ISSUE THREAD

**Issue by kichalla** [aspnet/BuildTools#216]
Currently SplitPackages cross compiles for .net core and net451. Check if we can avoid net451.
https://github.com/aspnet/BuildTools/blob/dev/src/SplitPackages/SplitPackages.csproj#L40
https://github.com/aspnet/BuildTools/blob/dev/src/SplitPackages/SplitPackages.nuspec#L10

**Comment by Eilon** [comment]
@kichalla can you try removing net451 and see if it works? If it works, go for it. If not, please spend only up to 37 minutes investigating. If you can't figure it out, we can close this bug.

**Comment by kichalla** [comment]
c11946aa85b477208f7ba836cc4a398a4afea05e
