### ISSUE TITLE
Re-enable  Json.NET version rule check

### ISSUE THREAD

**Issue by kichalla** [aspnet/BuildTools#220]
https://github.com/aspnet/BuildTools/commit/cd6ef9bd68fe01c9141cda13a276d76b3bafb040

**Comment by natemcmaster** [comment]
Could this be considered a dupe of https://github.com/aspnet/BuildTools/issues/208?

**Comment by kichalla** [comment]
Enabled the check with eac4856f481586a19cc13381ee0e19ae68df91c8

@natemcmaster let's discuss offline
