### ISSUE TITLE
Need to remove obsolete log that warns about unlisted packages

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#235]
We currently have a log message https://github.com/aspnet/BuildTools/blob/dev/src/NuGetPackageVerifier/Program.cs#L210 that says something like,
`Found 7 unlisted packages. Every package in the repo should be listed in exactly one package set. Running default or all rules on unlisted packages.`

Since we decided not to list any packages explicitly, I suggest we remove this log. 
Thoughts? @Eilon @natemcmaster

**Comment by natemcmaster** [comment]
https://github.com/aspnet/BuildTools/pull/361
