### ISSUE TITLE
[Discussion] NugetPackageVerifier

### ISSUE THREAD

**Issue by MaximRouiller** [aspnet/BuildTools#24]
Rules like this would be kind of neat for other package authors. 

Kind of like a baseline to ensure that your package have good metadata. 

Here are my questions:
- Any plans to spawn this tool in its own repository?
- Will this still work with the dotnet-cli? 
- Was this inspired from another tool or did you build it from scratch?
- Any point in anyone forking this code to make it reusable by the community?

**Comment by Eilon** [comment]
@MaximRouiller no current plan to do anything with this tool beyond what we need it for. The tool just scans NUPKG files, so it doesn't care how they were built.

The tool was inspired by (*ahem* I totally stole the code) from a different NuGet verification tool that the NuGet team wrote a long, long time ago.

If you think there's value in building a community tool based off of this, by all means I think that could be useful.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by MaximRouiller** [comment]
Nope. Nothing else to add.
