### ISSUE TITLE
Revert the temporary commit related to AssemblyLoadContext.GetAssemblyName's MissingMethodException

### ISSUE THREAD

**Issue by kichalla** [aspnet/BuildTools#255]
Issue in corefx: https://github.com/dotnet/coreclr/issues/11585

Commit to revert once the above issue is fixed: 83c7516741d02eafc3a32fc56e9f7a5efcadf9bf

**Comment by smitpatel** [comment]
@kichalla - The underlying issue is fixed already. Is there any issue in reverting this in dev branch? This commit was one of the changes when travis issue started surfacing. Trying to pin point root cause.

**Comment by kichalla** [comment]
@smitpatel So does this issue not repro anymore? https://github.com/dotnet/coreclr/issues/11585

if yes, sure we can revert in dev branch.

**Comment by smitpatel** [comment]
No exception thrown. Is that expected behavior?

**Comment by Eilon** [comment]
@kichalla looks like we should be able to revert the commit in dev.

**Comment by kichalla** [comment]
845697f6c5cd146fab5c7d4775f546e52a1cd7cb
