### ISSUE TITLE
ThirdParty.json shouldn't be tied to NuGetPackageVerifier

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#266]
Right now whenever we have to add an entry to third-party.json, we need get the latest build of NPV for it to work. We should instead have the json at a different location and have NPV read from it on every run. This would make this much simpler.

@ryanbrandenburg @pakrym

**Comment by pakrym** [comment]
Which different location do you have in mind?

**Comment by ajaybhargavb** [comment]
I was thinking Coherence-Signed but I checked and we also run this check as part of individual builds. So not sure what would be the right location. Do you have any suggestions?

**Comment by natemcmaster** [comment]
+1. We've been burned by this a few times now. We have to spin a new build of NGPV every time we need to change third-party dependencies.
