### ISSUE TITLE
GetGitCommitInfo "Unable to determine active git branch" on CI

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#298]
When Universe builds on TeamCity it produces the message "Unable to determine active git branch.".

This isn't a high priority, but it would be nice to clean it up so that it either found the branch or didn't complain when it happened on TC.

**Comment by natemcmaster** [comment]
IMO seems like a legit warning. We should configure TeamCity to checkout a branch instead of checking out in detached HEAD mode.

**Comment by ryanbrandenburg** [comment]
This is covered by aspnet/Coherence-Signed#622.
