### ISSUE TITLE
NuGetPackageVerifier is not catching many incorrect assembly versions

### ISSUE THREAD

**Issue by mikeharder** [aspnet/BuildTools#319]
It seems the NuGetPackageVerifier is not catching many incorrect assembly versions.  For example, on 7/14/17, the version of `Microsoft.IdentityModel.Protocols.OpenIdConnect` used in the product repos was `2.1.4`, but third-party.json still listed `2.1.3`, and there were no build failures:

https://github.com/aspnet/Security/blob/5485846b5c119a365ac3d004effc8aa97d987fce/build/dependencies.props#L6
https://github.com/aspnet/Security/search?utf8=%E2%9C%93&q=IdentityModelOpenIdVersion&type=
https://github.com/aspnet/BuildTools/blob/74a54c39ec904360242a969dc045584d988e7a1f/src/NuGetPackageVerifier/third-party.json#L29

**Comment by natemcmaster** [comment]
Yeah, I noticed the same thing, but didn't dig into it. Were there changes to which rules are set to run in the NuGetPackageVerifier.json file?

**Comment by mikeharder** [comment]
@ajaybhargavb is investigating for 2.0

**Comment by ajaybhargavb** [comment]
da17f2ae6f1755d882fa8c33019f1caaf5725b60
