### ISSUE TITLE
Determine if there's a way to execute PrereleaseDependenciesVersionRule a bit earlier for 3rd party dependencies

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#336]
For the 2.0.0 release, we had the rule disabled until we got RTM versioned partner packages. Unfortunately this meant we missed noting our test specification packages relied on pre-release packages until very late in the release. It would be nice if we could codify in the rule the list of packages we are certain will become RTM as part of a release and allow them to be marked pre-release while we're still in the process of acquiring final builds. i.e. Allow a RTM versioned package to reference a prerelease version of a well known list. We specifically want to avoid blanket terms such as any `System.*` in the list since the 2.0.0 list comprised of packages such as `System.Memory` which did not have an RTM version.

**Comment by pranavkm** [comment]
cc @mikeharder

**Comment by natemcmaster** [comment]
Is this rule still disabled?

**Comment by pranavkm** [comment]
I don't think we ever disabled the rule. The issue was to identify things that would eventually fail. Maybe this is no longer an issue with prodcon + NuGet build warnings.

**Comment by natemcmaster** [comment]
Ah, I see.

**Comment by Eilon** [comment]
Not a common enough problem, so closing.
