### ISSUE TITLE
Break down KoreBuild into composable commands

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#337]
build.ps1/sh is a monolith script that

1. Downloads KoreBuild
1. Downloads dotnet and .NET Framework reference assemblies (linux only)
1. Invokes `dotnet msbuild` on a sln file

It would be nice to breakdown KoreBuild into smaller commands so that we can better compose these steps.

**Proposal**
1. Move the main build logic from `build.ps1/sh` to `run.ps1/sh`.

    Syntax:
    ```
    ./run.{ps1,sh} <COMMAND> [<COMMAND_ARGS>...]
    ```

2. Keep a build.cmd for legacy reasons. This will forward to run.ps1
3. Add other sub-commands
    1. `install-tools`. Download required tools such as dotnet.exe SDK and runtimes
    2. `msbuild`. Executes the main solution build
    3. `push`. Executes push logic (uploading NuGet packages)

**Future**
More sub-commands could be added

`doctor` - a command to inspect the current environment. Helps identify potentially bad dev environments
`autoclean` - clear caches, old versions of korebuild, tools, etc.
`init` - downloads KoreBuild, nothing else
`update` - download/updates the KoreBuild version
`api-check` - command-line gestures for generating baselines and other API check features
`install-vs` - download and [install VS](https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio) with required VS features
`rev-version` - commands for automating version revving, pinning, etc.

**Comment by natemcmaster** [comment]
cc @ryanbrandenburg - `docker-build`?

**Comment by natemcmaster** [comment]
@ryanbrandenburg is there more work to do here?

**Comment by ryanbrandenburg** [comment]
I think we're good for now, we can add new commands as needed.
