### ISSUE TITLE
Add a TeamCity logger

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#345]
We should implement a logger that is better suited for TeamCity output. I've asked JetBrains about this and their recommendation was to use their dotnet CLI plugin instead. We prefer not to use these plugins but instead rely on scripts to work well for us, so we should consider making our own logger.

Featuers:

 - Log TeamCity blocks. Makes it easier to navigate output (we currently spit out ~100 MB of text).
 - Produce cleaner console output showing the KoreBuild lifecycle
 - Use flow ID to keep messages from parallel processes inline.

**Comment by smitpatel** [comment]
While we are there, provider an ability to intercept log messages and do processing for `ITestFailed`

**Comment by natemcmaster** [comment]
It's available now. Let's update build tools to use it.

https://github.com/JetBrains/TeamCity.MSBuild.Logger

**Comment by ryanbrandenburg** [comment]
In that case let's re-open the issue as well 😄

**Comment by natemcmaster** [comment]
Had to revert #550. See JetBrains/TeamCity.MSBuild.Logger#3

**Comment by natemcmaster** [comment]
This is done. See https://github.com/aspnet/BuildTools/blob/dev/docs/Logging.md for details on enabling it. I've left it off for our our Universe builds because it adds ~15 minutes to the build.
