### ISSUE TITLE
Stop installing .NET Core 1.0 and 1.1 by default

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#347]
Most repos only need .NET Core 2.0. A few need 1.0 and 1.1 for their build tools. Very few require a runtime for tests. We can stop installing these by default once we update the tools, but should find a way for the repos that still need it for testing to express their dependency on those runtimes.

**Comment by ryanbrandenburg** [comment]
This will likely depend on #348.

**Comment by natemcmaster** [comment]
Repos using KoreBuild that still need .NET Core 1.x, as far as I can tell

- https://github.com/aspnet/Coherence/blob/dev/tools/CoherenceBuild/CoherenceBuild.csproj
- https://github.com/aspnet/AspNetCoreModule/blob/dev/test/AspNetCoreModule.TestSites.Standard/AspNetCoreModule.TestSites.Standard.csproj
- https://github.com/aspnet/MetaPackages/blob/dev/tools/dotnet-deb-tool-consumer/dotnet-deb-tool-consumer.csproj
- https://github.com/aspnet/EntityFramework/blob/dev/benchmarks/EFCore.Benchmarks.EFCore1/EFCore.Benchmarks.EFCore1.csproj

**Comment by ryanbrandenburg** [comment]
Are there good reasons why each of those are still netcoreapp1.0 or have they just not been updated yet?

**Comment by natemcmaster** [comment]
ASP.NET Core Module intentionally uses RTM dependencies instead of nightlies. Although I suppose that could change too.
EF Core benchmarks netcoreapp1.1 intentionally.

The others are good candidates for an upgrade.

**Comment by natemcmaster** [comment]
@smitpatel do you use KoreBuild to run the EF Core 1.1 benchmarks? If so, we should make changes to EF Core so we ensure that runtime is still installed after we stop installing it by default.

**Comment by smitpatel** [comment]
We use KoreBuild to install dotnet but we are using it from Path variable. I suppose that means that we are using dotnet latest to run older builds. It would be ok to remove installation. If they are needed then it would be proper to have them installed on CI agents as a software rather than by build script.
