### ISSUE TITLE
KRB4002 can't be suppressed if a <PackageReference> needs more than one NoWarn

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/BuildTools#392]
This line of code: https://github.com/aspnet/BuildTools/blob/07229f1322a50424c2830032e0f9c1786cb0e865/modules/KoreBuild.Tasks/Policy.VersionRestrictions.targets#L14

... is checking whether the `NoWarn` value exactly equals `KRB4002`. This is OK if that's the only warning suppression you want to use. But if you're trying to suppress `KRB4002` *and* something else, it doesn't appear there's any way to do that.

Could the `WithMetadataValue` check be replaced by a substring search, or a search through the value split on some separator (space, comma, or semicolon - whatever matches convention best)?

**Comment by SteveSandersonMS** [comment]
It's not blocking, but I did have to use `DisablePackageReferenceVersionRestrictions` as a workaround: https://github.com/aspnet/templating/blob/dev/test/Templates.Test/Templates.Test.csproj#L7

It would be great to remove that workaround when there's a better way.

**Comment by natemcmaster** [comment]
Closing as wontfix. I'm removing PackageLineup soon, so KRB4002 won't exist anymore. See #455.
