### ISSUE TITLE
Detect if machine is 32-bit only in build.ps1

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BuildTools#397]
Currently our build scripts fail on machines that are 32-bit only. Though this is rarely a blocker or issue for us, but external contributers may be using 32-bit machines (Ex [aspnet/dependencyinjection](https://github.com/aspnet/DependencyInjection/issues/579#issuecomment-328591130)). @natemcmaster mentioned we could check PROCESS_ARCHITECTURE to see if the machine is 32-bit or 64-bit.

**Comment by natemcmaster** [comment]
Edge case to consider: PowerShell can run in x86 mode on x64 machines ("PowerShell (x86)"). In this case, PROCESSOR_ARCHITEW6432 will be set to AMD64 and PROCESS_ARCHITECTURE will be x86. Should we use the true CPU arch or the shell arch in this case?

**Comment by jkotalik** [comment]
Ah I didn't realize that PROCESS_ARCHITECTURE returned the current shell's architecture. We should probably base it off the true CPU's arch.

**Comment by ryanbrandenburg** [comment]
A secondary concern here is that once our docker stuff is up and running we should test some things on 32-bit systems so that we know about this kind of bug.

**Comment by ryanbrandenburg** [comment]
Let's close it for now, we can re-open it if/when we have specific cause to.
