### ISSUE TITLE
Make (or use) .NET Framework ref assemblies as a nuget package

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#399]
Reduce the number of external things that have to be installed in order to compile.
Also, it will reduce the things that are downloaded on Linux builds where .NET Framework isn't actually used.

**Comment by davidfowl** [comment]
:\ does anybody do this? Is this something we'd really want to own?

**Comment by natemcmaster** [comment]
This would be just for us. We've asked netfx to make these a few times, but after a few years of waiting, I think it's safe to say it's not coming.

**Comment by Eilon** [comment]
Previous related issue: https://github.com/aspnet/KoreBuild/issues/211

**Comment by natemcmaster** [comment]
Note to a potential future implementer: in linux, we acquire netfx assemblies with the "get-netfx.sh" script. If we move to nuget, that piece of the bootstrapper can be deleted.

**Comment by dasMulli** [comment]
What about the ones at https://dotnet.myget.org/feed/dotnet-core/package/nuget/Microsoft.TargetingPack.NETFramework.v4.5.2 ?

**Comment by natemcmaster** [comment]
That is one possibility. We're looking into it.

**Comment by natemcmaster** [comment]
Roslyn has some packages too that may provide this. https://github.com/dotnet/roslyn/blob/master/build/Targets/Settings.props#L68

**Comment by hubuk** [comment]
@dasMulli 
Microsoft.TargetingPack.NETFramework.v* packages lack some important directories described in this issue: https://github.com/dotnet/corefx/issues/25012
With this change they can replace https://aspnetcore.blob.core.windows.net/buildtools/netfx/4.6.1/netfx.4.6.1.tar.gz used currently.

**Comment by natemcmaster** [comment]
Good to know. Thanks for the heads up @hubuk .

**Comment by natemcmaster** [comment]
@tmat do you happen to know if roslyn's reference assembly nuget packages are (1) open source and (2) reference-able as a PackageReference?

**Comment by tmat** [comment]
@natemcmaster @jaredpar Builds the package from here: https://github.com/jaredpar/xcopy-msbuild/blob/master/build-reference-assemblies.ps1. The package is available in roslyn-tools feed:
https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.ReferenceAssemblies

**Comment by natemcmaster** [comment]
Thanks @tmat. That package looks almost identical to a package we made too: https://dotnet.myget.org/feed/aspnetcore-tools/package/nuget/NETFrameworkReferenceAssemblies. I don't have any plans to work on this at the moment, but ideally, we'd love to be able to do this. 
```xml
  <ItemGroup>
    <PackageReference Include="NETFramework.TargetingPack" Version="4.6.1" />
  </ItemGroup>
```

**Comment by tmat** [comment]
I believe there are work items on the dotnet SDK team to make something like that happen. @nguerrera

**Comment by nguerrera** [comment]
@dsplaisted had a proposal, but I think this falls on corefx. cc @Pertermarcu

**Comment by natemcmaster** [comment]
I've been watching https://github.com/dotnet/sdk/issues/335. Is the best one to use to keep track of progress on this?

**Comment by nguerrera** [comment]
The corefx team has *unofficial* targeting pack nupkgs. I think they need to make them official and then we can build support for using them into the SDK. cc @weshaggard.

**Comment by weshaggard** [comment]
I believe @terrajobst owns writing up a design. However at this point there are no concrete plans around doing this work.

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/dotnet/designs/pull/33 and https://github.com/dotnet/sdk/issues/335

**Comment by natemcmaster** [comment]
Changed our minds again. Let's use the ref packs the roslyn team made and put on https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json. cref https://github.com/dotnet/roslyn-tools/pull/190.

**Comment by natemcmaster** [comment]
This was completed in https://github.com/aspnet/AspNetCore/pull/6995
