### ISSUE TITLE
Upgrading MinimumVisualStudioVersion to 15.0.26730.03 (15.3) in all of our dev branches

### ISSUE THREAD

**Issue by jkotalik** [aspnet/BuildTools#403]
As dotnet core 2.0 is not supported on any version of visual studio below 15.3, we should upgrade the MinimumVisualStudioVersion to 15.3 which, after a ton of searching, is 15.0.26730.03. This is useful for external contributers, as they will immediately know their version of visual studio is out of date. 
@natemcmaster @ryanbrandenburg

**Comment by natemcmaster** [comment]
What does this correspond to? 15.3.4 or just 15.3.0?

**Comment by jkotalik** [comment]
I believe 15.3.0. There was very poor documentation online about it though, we should probably ping someone on the VS team to confirm.

**Comment by jkotalik** [comment]
Should we support 15.3 preview builds too?

**Comment by natemcmaster** [comment]
Nah, 15.3 is RTM. It's okay to ask people to have the latest stable release of VS.

**Comment by Eilon** [comment]
This sounds like a good idea, let's do it across all our SLNs in all our repos. The affected repos should be the ones tagged with `asp-product`: https://github.com/aspnet?utf8=%E2%9C%93&q=topic%3Aaspnet-product&type=&language=

**Comment by jkotalik** [comment]
All repos in Universe have been updated except for EntityFramework. @Eilon @natemcmaster here are the remaining repos that are not private or obsolete that have not been updated. 
- BuildTools
- Entropy
- Coherence
- Webhooks
- Templating

**Comment by natemcmaster** [comment]
You can update BuildTools too. Otherwise, looks good.

**Comment by Eilon** [comment]
Great!
