### ISSUE TITLE
ApiCheck examples?

### ISSUE THREAD

**Issue by lovemaths** [aspnet/BuildTools#404]
It would be nice to have some examples or a more detailed documentation showing how to use this tool. The current documentation is very confusing. It only shows a list of options, but doesn't say which one is required/optional and how to figure out the value of these options.

**Comment by Eilon** [comment]
This is a tool meant for internal ASP.NET/EF Core usage, so we have no plans to document it at this time. We have a little bit of info at https://github.com/aspnet/BuildTools/wiki/Api-Check, plus you can look at how it's used in the build, but please be warned that this is not an officially supported product.
