### ISSUE TITLE
Have KoreBuild set LangVersion to 7.1

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BuildTools#408]
Rather than specifying the latest language version on a per project or per repo basis, KoreBuild can set it globally. The current recommended version is 7.1.

See https://github.com/aspnet/Hosting/pull/1222#discussion_r139603778

**Comment by Eilon** [comment]
@Tratcher do you want to take a crack at this?

**Comment by Tratcher** [comment]
Fixed using Internal.AspNetCore.Sdk.  This covers all src and tests, but not samples.
