### ISSUE TITLE
Fix generate api check baselines task

### ISSUE THREAD

**Issue by javiercn** [aspnet/BuildTools#410]
- [ ] There is a target to run it as part of the build on a repository.
- [ ] There is a way to disable it though an MSBuild property (off by default).
- [ ] Baselines are generated for new assemblies.
- [ ] Breaking changes are deleted upon the generation of new baselines.

**Comment by javiercn** [comment]
@ryanbrandenburg

**Comment by Eilon** [comment]
Load balancing to @ryanbrandenburg . Please make sure changes are reviewed by @natemcmaster and @javiercn .

**Comment by javiercn** [comment]
It means that you should remove all api check related files (existing baselines + breaking changes files) and invoke the tool to create new ones.

**Comment by javiercn** [comment]
Or better yet, just invoke the tool to generate a baseline and put that baseline in the obj/ folder. Then when we want to commit the new baselines we just need an additional task that replaces the existing one with the freshly generated and removes the breaking changes files.
