### ISSUE TITLE
Support F# projects in new lineups system

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/BuildTools#414]
Currently, if you have an `fsproj` referenced via `<ProjectReference>` from some `csproj`, then running `build /t:Restore` fails with:

```
error KRB1001: Package references have not been pinned. Run './build.cmd /t:Pin'. [some\path\FSharpWebSite.fsproj]
```

At a guess, maybe some of the code in buildtools works by looking for `csproj` files explicitly rather than allowing arbitrary project types ([example](https://github.com/aspnet/BuildTools/blob/2fdcbd3f8c1461caed668ebeaf42c9545d30fcbb/files/KoreBuild/modules/solutionbuild/module.targets#L9)).

It would be great if we were able to support `.fsproj` because in the past we had functional tests covering ASP.NET apps written in F#. These had to be disabled because of build system issues, but it would be ideal to bring them back.

**Comment by natemcmaster** [comment]
Closing as I finished removing lineups from the 'dev' branch of aspnetcore, and will remove it from buildtools altogether sometime soon #455. fsproj should work with the existing dependencies.props approach. These tools aren't csproj specific.

Side note: if you find more areas in which our tooling is too specific to csproj and prevents you from using fsproj, let me know. The [example](https://github.com/aspnet/BuildTools/blob/2fdcbd3f8c1461caed668ebeaf42c9545d30fcbb/files/KoreBuild/modules/solutionbuild/module.targets#L9) you pointed to was only for calling 'dotnet pack'. I'm not aware of any packages we ship that are written in F#, but if we ever did, this would certainly cause issues.
