### ISSUE TITLE
Make KoreBuild targets incremental

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#421]
Problems today:

 - We always delete `artifacts/`
 - Individual steps depend on each other. This means you can't invoke `/t:Test` without causing a re-build
 - Undefined outputs

Changes:

### Assert everything in `artifacts/` is a known artifact
Rules:
 - Anything that is written into `artifacts/` should be included in the `Artifact` item group.
 - No writing to artifacts allowed after `Package`. e.g. tests should not produce artifacts

### Make targets incremental
Targets should use Inputs/Outputs to avoid recompiling/repackaging when necessary

### Change the default lifecycle for individual steps. 

Today:
```xml
  <PropertyGroup>
    <PrepareDependsOn></PrepareDependsOn>
    <RestoreDependsOn>Prepare</RestoreDependsOn>
    <CompileDependsOn>Restore</CompileDependsOn>
    <PackageDependsOn>Compile</PackageDependsOn>
    <TestDependsOn>Package</TestDependsOn>
    <VerifyDependsOn>Test</VerifyDependsOn>
    <BuildDependsOn>Verify</BuildDependsOn>
  </PropertyGroup>
```
Change:
```xml
  <PropertyGroup>
    <PrepareDependsOn></PrepareDependsOn>
    <RestoreDependsOn></RestoreDependsOn>
    <CompileDependsOn></CompileDependsOn>
    <PackageDependsOn></PackageDependsOn>
    <TestDependsOn></TestDependsOn>
    <VerifyDependsOn></VerifyDependsOn>
    <BuildDependsOn>Prepare;Restore;Compile;Package;Test;Verify</BuildDependsOn>
  </PropertyGroup>
```

This would preserve the default behavior

**Comment by ryanbrandenburg** [comment]
I did not know the Inputs/Outputs thing even existed, that should be really useful, both for rebuilding and also forced documentation about what exactly a Target needs and does.

**Comment by natemcmaster** [comment]
Prototype: https://github.com/natemcmaster/AspNetBuildTools/commit/9c944e170f7924d194967b7a7e5f0654a0ff8b2d

**Comment by natemcmaster** [comment]
No plans to do this. We'll converge to Arcade instead.
