### ISSUE TITLE
Clone MVC repo project, bulid and then meet some warnings:"SourceLink not enabled because RepositoryRoot wasn't set. "

### ISSUE THREAD

**Issue by Eilon** [aspnet/BuildTools#427]
Original issue: https://devdiv.visualstudio.com/DevDiv/_workitems?id=509637&fullScreen=false&_a=edit

Maybe something in [this file](https://github.com/aspnet/BuildTools/blob/687e37e79ef0ae7546cda3066cae303474d72bb9/src/Internal.AspNetCore.Sdk/build/Git.targets)?

![image](https://user-images.githubusercontent.com/202643/31626264-ea4ee4a2-b25d-11e7-86b1-e4c4cb7f4ede.png)

**Comment by ryanbrandenburg** [comment]
@natemcmaster and I discussed this and we think the best solution is to add `RepositoryRoot` to `Directory.Build.props` like a couple of repos [already have](https://github.com/aspnet/EntityFrameworkCore/blob/61952a43a17785490c041a71ba573455a04f94b2/Directory.Build.props#L10). This has the benefit of making VS behave more closely to KoreBuild.
