### ISSUE TITLE
Add install-vs command

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#445]
In https://github.com/aspnet/BuildTools/issues/428, I added support to _validate_ that VS is installed and has required workloads. To take this one step further, it would be nice if users or CI agents could also start a VS installation from command-line.

Example:
korebuild.json
```json
{
  "toolsets": {
     "visualstudio": {
       "required": [ "windows" ],
       "minVersion": "15.4",
       "requiredWorkloads": [ "Microsoft.VisualStudio.Workload.VCTools" ]
     }
   }
}
```
```
run.ps1 install vs
```

Ideas:
We could generate an installation manifest and pass it to the VS installer.

 - Visual Studio supports defining installation parameters as a file. https://docs.microsoft.com/en-us/visualstudio/install/automated-installation-with-response-file

Example:
```
vs_enterprise.exe --in visualstudio.json
```
```json
{
  "installChannelUri": ".\\ChannelManifest.json",
  "channelUri": "https://aka.ms/vs/15/release/channel",
  "installCatalogUri": ".\\Catalog.json",
  "channelId": "VisualStudio.15.Release",
  "productId": "Microsoft.VisualStudio.Product.Enterprise",

  "installPath": "C:\\VS2017",
  "quiet": false,
  "passive": false,
  "includeRecommended": false,
  "norestart": false,

  "addProductLang": [
    "en-US"
    ],

    "add": [
        "Microsoft.VisualStudio.Workload.NetWeb",
        "Microsoft.VisualStudio.Workload.VCTools"
    ]
}
```

cc @jkotalik

**Comment by jkotalik** [comment]
@muratg can we budget some of my time to do this? Numerous people have pinged me trying to figure out what tools are required to build IISIntegration. Also, on VMs, I don't want to require people installing VS or struggling to figure out what dependencies are needed. 
cc/ @mikeharder

**Comment by natemcmaster** [comment]
By the way, checkout https://github.com/aspnet/Infrastructure/blob/master/BuildAgent/SetupScripts/BuildAgent_VisualStudio.ps1 for automating running the VS installer.

**Comment by jkotalik** [comment]
Yep! We should be able to translate those from our CI to local machines.

**Comment by muratg** [comment]
What's the estimated cost for this?

**Comment by natemcmaster** [comment]
small, 1-2 days

**Comment by muratg** [comment]
:+1:  

@jkotalik let's talk about this once you have time from the current ANCM work.
