### ISSUE TITLE
Repo build artifacts have wrong transitive versions 

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BuildTools#446]
If I build a repo and look at the artifacts directory it produces packages like Microsoft.AspNetCore.TestHost.2.1.0-preview1-t000.nupkg. However, the dependencies from this package to other packages in the same repo use 2.1.0-preview1. If I then try to consume this package from another repo by adding the artifacts directory as a feed then restore fails because it can't find  2.1.0-preview1 of the dependent packages. To work around this I have to directly reference all of the transitive dependencies from that repo.
e.g. 
```
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.1.0-preview1-t000" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.1.0-preview1-t000" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.1.0-preview1-t000" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.1.0-preview1-t000" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="2.1.0-preview1-t000" />
```

Fix: local dependencies should include the full version so they can be resolved transitively.

**Comment by natemcmaster** [comment]
This happens if you use Visual Studio to restore or pack instead of command-line. A better solution would be to add a fallback build number to version.props as we did here:

https://github.com/aspnet/Scaffolding/blob/rel/2.0.1/version.props#L7

**Comment by natemcmaster** [comment]
This should have been fixed now in our repos by adding a fallback `<BuildNumber>` to version.props. Re-open if you're still having issues.
