### ISSUE TITLE
Repo build artifacts need time-stamped versions

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BuildTools#447]
When building a repo locally the packages in the artifacts directory are all versioned 2.1.0-preview1-t000. If you consume these packages from any other repo or project then they are added to your machine cache. The problem is that when you make changes and rebuild these packages they still have the same version so you can't restore them again elsewhere without closing all instances of VS and purging your local machine cache first. This makes for a slow and tedious iteration process when developing new features or fixes cross-repo.

This used to work by using a date/time stamp in the package version so each rebuild would produce uniquely named artifacts. It's not clear why it this was regressed.

@natemcmaster

**Comment by natemcmaster** [comment]
This behavior is by-design and was changed back in August. See https://github.com/aspnet/BuildTools/pull/309.

For cross-repo work, I recommend `build.cmd /p:IncrementalVersion=true` to generate a random, time-based version. Or you can manually increment via `build.cmd /p:BuildNumber=xyz`

**Comment by Eilon** [comment]
Closing for the reason that @natemcmaster mentioned.
