### ISSUE TITLE
Code cleanup in bootstrappers

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#449]
Let's address the comments @dougbu raised about the Bootstrapper scripts in https://github.com/aspnet/Performance/pull/247#pullrequestreview-72927481 here, then we can move them out to every repo at once.

**Comment by natemcmaster** [comment]
As long as were at it, one think I find annoying about how we parse arguments in run.sh is that the 'command' has to be the first argument. For example, these don't work
```
run.sh --update upgrade deps
run.sh upgrade deps  --update 
```
Instead, you have to put bootstrapper args between the 1st argument and anything else
```
run.sh upgrade  --update  deps
```

**Comment by natemcmaster** [comment]
_Triage team:_ closing this as low priority.
