### ISSUE TITLE
Reproducible builds: time-based generated code

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#452]
https://wiki.debian.org/ReproducibleBuilds/Howto
https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal

Recommended solutions in order of preference:

- Support SOURCE_DATE_EPOCH or omit the timestamp entirely by default, so that other projects using this build tool don't also need to do the below.
- Prevent the timestamp from being written entirely in the build products.
- Tell the tools to use the timestamp of “0” if the timestamp is not used.
- Tell the tools to use the timestamp of the last debian/changelog entry.
- Strip timestamps at the end of the build process.
- Replace timestamps at the end of the build process.

Example:
We generate AssemblyFileVersion from the current timestamp. This makes build non-reproducible because each build changes the binary output.

**Comment by Eilon** [comment]
From triage: Justification: not important enough. We currently don’t care about deterministic build output.
