### ISSUE TITLE
Support variables in dependencies.props that shouldn't be overridable

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#463]
Some package version variables shouldn't be overriden by upgrade automation. We should support splitting variables into two categories.

### Current
All variables are in one group and could be overriden by DotNetPackageVersionPropsPath
```xml

  <PropertyGroup Label="Package Versions">
    <MicrosoftAspNetCorePackageVersion>2.1.0-preview1-123</NewtonsoftJsonPackageVersion>
    <XunitPackageVersion>2.3.0</XunitPackageVersion>
  </PropertyGroup>

  <Import Project="$(DotNetPackageVersionPropsPath)" Condition=" '$(DotNetPackageVersionPropsPath)' != '' " />

```

### Proposal
Put 'stable' variables after the DotNetPackageVersionPropsPath import.

```xml
  <PropertyGroup Label="PackageVersions:Internal.AspNetCore.Universe.Lineup">
    <MicrosoftAspNetCorePackageVersion>2.1.0-preview1-123</NewtonsoftJsonPackageVersion>
  </PropertyGroup>

  <Import Project="$(DotNetPackageVersionPropsPath)" Condition=" '$(DotNetPackageVersionPropsPath)' != '' " />

  <PropertyGroup Label="PackageVersions:Pinned">
    <XunitPackageVersion>2.3.0</XunitPackageVersion>
  </PropertyGroup>

```

**Comment by ryanbrandenburg** [comment]
Isn't the solution to this just to name the property something other than `(package.Name)PackageVersion`?

**Comment by natemcmaster** [comment]
That's another solution too. We generally know the shape of variables imported in DotNetPackageVersionPropsPath. However, that still leaves open the possibility that some future DotNetPackageVersionPropsPath  file might override it. It would still be better to put variables after the import to avoid the possibility of an external override.

**Comment by natemcmaster** [comment]
Fixed with https://github.com/aspnet/BuildTools/pull/706
