### ISSUE TITLE
Curl fails on OSX in Travis-CI

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#470]
We get the error: `curl: (56) SSLRead() return error -36` when trying to download using curl quite frequently. We notified the [Travis folks](https://github.com/travis-ci/travis-ci/issues/7502#issuecomment-288450654). But there doesn't seem to have been much movement.

So far the best option I can come up with is to change `dotnet-install.sh`  to prefer wget and install wget for any travis.yml having troubles (or just by default).

@natemcmaster  had looked into this before so I'd like to hear his feedback.

**Comment by natemcmaster** [comment]
Even when we switched to wget, we still get networking issues with macOS. IMO we should consider dropping it altogether and just build for Linux on Travis.

**Comment by ryanbrandenburg** [comment]
I'd be fine with that at least until they fix that issue. We still get coverage of OSX via TC, and it would let people trust the success or failure of PR tests more, which I think will lead to LESS failures on TC.

**Comment by Eilon** [comment]
We're looking to stop using Travis perhaps entirely, so closing this.
