### ISSUE TITLE
Create a myget package trimmer

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#479]
We currently preserve all myget packages on our feeds. However, once we release an RTM version of a package, we don't need all the pre-release versions anymore. We should investigate creating a myget package trimmer for prune old packages after we RTM to nuget.org.

Logic:
```c#
foreach (var pkg in packagesOnFeed)
{
    if (IsPackageVersionRtm(pkg.Version) || IsPackageVersionOnNugetDotOrg(pkg.Version)) 
       continue;
    var versionAsRtm = GetRtmVersion(pkg.Version)
    if (!feed.Contains(versionAsRtm)) 
       continue;
    Delete(pkg)
}
```

**Comment by mikeharder** [comment]
Are previews pushed to nuget.org (e.g. `2.0.0-preview1-final`) considered an "RTM Version"?  Or only non-previews like `2.0.0`?

**Comment by natemcmaster** [comment]
IMO IsPackageVersionRtm should be true for anything we shipped to nuget.org

**Comment by mikeharder** [comment]
Sounds fine to me, just wanted to clarify.

**Comment by Eilon** [comment]
Do we sometimes have "build tools" that are RTM but not on NuGet.org? Or things like `.Sources` packages?

**Comment by natemcmaster** [comment]
Yes. Any "noship" package. For example, Microsoft.AspNetCore.Testing, .Sources packages, and build tools packages.

**Comment by natemcmaster** [comment]
FYI myget introduced more powerful retention settings recently, so I don’t think we need this anymore. 
https://docs.myget.org/docs/reference/package-retention
