### ISSUE TITLE
Update PackageOwnershipRule to take advantage of reserved prefixes

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#484]
NuGet.org added a feature where owners can reserve a prefix so that a family of packages that share this can only be uploaded by the specific owner. As part of this change, the AspNetCore team already owns the following prefixes:

* Microsoft.AspNetCore.*
* Microsoft.AspNet.*
* Microsoft.CodeAnalysis.Razor
* Microsoft.Data.Sqlite.*
* Microsof.Dotnet.*
* Microsoft.Extensions.*
* Microsoft.EntityFrameworkCore.*
* Microsoft.Net.Http.*
* Microsoft.Owin.*
* Microsoft.VisualStudio.*

The check in the tool needs to be updated to exclude any package that starts with this prefix (since we do not need to explicitly squat on those ids). The workflow for package reservation needs to also be updated to account for this new prefix ownership requirement.

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by Eilon** [comment]
Have some big concerns around this, see here: https://github.com/aspnet/BuildTools/pull/511#pullrequestreview-82375886
