### ISSUE TITLE
API Check does not understand `TypeForwardedTo`

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#485]
This issue not only mandates redundant breaking change descriptions but also means we have no way to check whether the type forwarding destination remains compatible with the original type.

For example, the MVC ApiExplorer assembly type forwards eight types to the Abstractions assembly in the project's [AssemblyInfo.cs file](https://github.com/aspnet/Mvc/blob/008a562bf5b1ab89e4b83c60faaabd1d12ffcb82/src/Microsoft.AspNetCore.Mvc.ApiExplorer/Properties/AssemblyInfo.cs#L6-L13).

The commit that did this (https://github.com/aspnet/Mvc/commit/07c22f2b29a684cd3371d792e77cbb55523f0f1f) had to **also** include breaking change descriptions for the same types. The updated descriptions were last found in the project's [breakingchanges.netcore.json file](https://github.com/aspnet/Mvc/blob/38712609bb2291202bfa760ee62348691de0ddae/src/Microsoft.AspNetCore.Mvc.ApiExplorer/breakingchanges.netcore.json#L2-L33). (The breaking changes went away in https://github.com/aspnet/Mvc/commit/a8eda83222711a4ee63307d1c71d184a92359351#diff-fbf88c3372073b371a0299db7fd4c676, when the API Check files were reset for the 2.0.0 release.)

**Comment by dougbu** [comment]
Self-assigning because I'll soon need to create additional type forwards.

**Comment by dougbu** [comment]
Information needed to fix this bug is not available on .NET Framework. Options include:
1. Fix bug only on .NET Core App 2.1, using the `Assembly.GetForwardedTypes()` method (added in 2.1). This could result in odd inconsistencies between baseline and breaking change listings for cross-compiled assemblies. But, that downside may be irrelevant because Asp.NET Core contains very few `[TypeForwardedTo]` attributes, they are all in one assembly (Microsoft.AspNetCore.Mvc.ApiExplorer.dll), and that assembly targets only .NET Standard 2.0. Of course, inconsistencies could come up in the future&hellip;
2. Use System.Reflection.Metadata to find forwarded types on all platforms. The necessary APIs appear to exist there. (See [this question](https://github.com/dotnet/corefx/issues/19713#issuecomment-301137320) and [answer](https://github.com/dotnet/corefx/issues/19713#issuecomment-301137784) in dotnet/corefx#19713.)
3. Wait for something like #203 and #204 i.e. move to System.Reflection.Metadata then fix this bug with that infrastructure. This bug could be another reason (beyond API Check breaking every time we change or add TFMs) to make that move.

**Comment by dougbu** [comment]
@natemcmaster, @javiercn, @ryanbrandenburg, @Eilon, @davidfowl your thoughts on the above options?

**Comment by dougbu** [comment]
FYI https://github.com/natemcmaster/AspNetBuildTools/tree/apicheck is more up-to-date than #203 / #204 (though still 183 commits behind `dev` in aspnet/BuildTools).

**Comment by javiercn** [comment]
@dougbu Option 1 seems way cheaper than the other ones and less risky, so I think it's the best course of action.

Changing API check to move along with our targeted TFMs is something very cheap to do. @davidfowl did it the other day to move it to 2.1 and the change seemed simple enough.

**Comment by natemcmaster** [comment]
Still am, and always will be, in favor of Option 3. @javiercn has done a good job of writing lots of tests which reduces the risk of refactoring to use Sys.Ref.Metadata. I think the gains of this refactoring are worth it, as I've previously listed in #198

**Comment by ryanbrandenburg** [comment]
I agree with @natemcmaster on this one, if this fixes a known, repeating, problem lets invest the time now to save future effort.

**Comment by javiercn** [comment]
@ryanbrandenburg I don't believe it is worth if you compare the costs of it. Updating the tool takes 30 min to 1h once or twice a year.

Updating the tool to use System.Reflection.Metadata will probably take in the most optimistic case 1 day of work (and it will most likely to be between 4 days and 1 week). So in order for the rewrite to payoff we would have to do 8 more releases at the very least, 32 if you count 4 days and 56 if it takes you 1 week. 
Even if double or quadruple the cost of updating the tool it still takes around 4 releases (at a 6 month cadence of release) or around 2 years for this change to pay off.

This is my reasoning, but I will let you guys and @Eilon decide.

@natemcmaster Even with the relatively decent amount of tests for the tool, running it against our repos still uncovered a few bugs and took me a few days to integrate, so I wouldn't underestimate the amount of risk involved in switching to a different implementation.

**Comment by Eilon** [comment]
If anyone is deeply passionate about implementing a change to use S.R.MD or to Roslyn, please talk to me so we can come up with a plan. I share @javiercn 's concerns and want to discuss the details with whoever is interested.

**Comment by javiercn** [comment]
Agree with @eilon. If we change something I would rather raise the abstraction level here and use something Roslyn based (Maybe their Symbols API). But I don’t think the cost/risk/benefit makes it worth it. That said I think it would be OK to timebox an effort to try and prototype an alternative and decide after that.

**Comment by davidfowl** [comment]
We could use mono.cecil (which @Eilon hates) or CCI (which the CLR team still uses an maintains). It has a higher level object model similar to reflection and is used in a bunch of their tools.

**Comment by javiercn** [comment]
@davidfowl I share @Eilon 's feelings for mono.cecil. That's why I suggested Roslyn instead of anything else (yet another API our devs are not familiar with)

**Comment by javiercn** [comment]
@dougbu What route are you going to go with?

**Comment by dougbu** [comment]
@javiercn I'm doing option 1.

**Comment by dougbu** [comment]
ef83157a1e
