### ISSUE TITLE
Figure out how to update CLI by hand

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#508]
We're waiting on PCP elements to be more real, but in the mean time we need to update CLI pieces at least somewhat.

**Comment by natemcmaster** [comment]
We do this all the time. Update the sdk.version file, create a version of build tools, and make sure that universe still builds with it.

https://github.com/aspnet/BuildTools/pull/457

**Comment by ryanbrandenburg** [comment]
@mikeharder looks like we should be able to just update [these](https://github.com/aspnet/BuildTools/tree/dev/files/KoreBuild/config) files to the version of the SDK and Runtime we want. @javiercn I think you were in on this conversation too, possibly as the original asker?
