### ISSUE TITLE
Expose NuGet package artifacts in AppVeyor

### ISSUE THREAD

**Issue by khellang** [aspnet/BuildTools#518]
Are you building NuGet packages as part of PR builds?

If you are, it would be helpful if you could [set up AppVeyor](https://www.appveyor.com/docs/packaging-artifacts/) to pick up and expose those artifacts.

Would make it easier to pick up a patched package from a PR without it being merged first.

**Comment by natemcmaster** [comment]
Yes, we build nupkgs in appveyor builds. I think you're the first to ask for appveyor to capture the artifacts so we've just never configured it.

cc @Eilon - I can't think of any reason _not_ to.

**Comment by Eilon** [comment]
We only publish Authenticode-signed binaries, and these binaries aren't signed, so I don't think we can enable it without getting the wrath of various powers.

**Comment by khellang** [comment]
> We only publish Authenticode-signed binaries, and these binaries aren't signed, so I don't think we can enable it without getting the wrath of various powers.

But this isn't _publishing_. It's merely exposing the packages for use in development. It's basically a bit more convenient than building the packages locally.

**Comment by khellang** [comment]
BTW, this request came out of a real world case where Kestrel had an issue with `Content-Length: 0` and WebSockets, and a client in the wild that would always send this header (see https://github.com/aspnet/KestrelHttpServer/pull/2217).

**Comment by forki** [comment]
@Eilon can you please reopen? This is not about pushing bits to myget. It's just that people can download the PR artifacts and test locally. Completely different story

**Comment by Eilon** [comment]
I understand, but it's a matter of policy that we release only signed binaries. I realize it's just AppVeyor creating its own drops, but that doesn't avoid the policy. Anyone can certainly clone the PR branch and create their own build - it would be otherwise identical to the build produced by any other system.

**Comment by forki** [comment]
No it's not even a release in any sense. It's just build artifacts. Like the output in the log. And no you can't do it locally because build is red on my machine. (but I found a way to create the nupkgs anyway).
