### ISSUE TITLE
The build script should install the Microsoft.AspNetCore.All shared framework

### ISSUE THREAD

**Issue by javiercn** [aspnet/BuildTools#525]
I ran into this when working on a PR in the templates repository.

When I tried to build an app targeting .net core it complained that it couldn't find a suitable SDK.

I worked around it by picking up the apropiate SDK version from the CI and placing it on my machine.

/cc: @natemcmaster @JunTaoLuo @pranavkm @muratg 

P.S: I was also forced to target netcoreapp 2.1 as part of my changes.

**Comment by natemcmaster** [comment]
already aware and working on it: https://github.com/aspnet/BuildTools/pull/522

**Comment by natemcmaster** [comment]
Finished with #522. The shared fx is installed on `build.cmd /t:Restore` when this is added to your repo.props file.

```xml
<ItemGroup>
   <AspNetCoreRuntime Include="$(MicrosoftAspNetCoreAllPackageVersion)" />
</ItemGroup>
```
