### ISSUE TITLE
Allow configuration of public key token in AssemblyStrongNameRule

### ISSUE THREAD

**Issue by joelverhagen** [aspnet/BuildTools#54]
Right now, `AssemblyStrongNameRule` is hardcoded to a specific strong name. Right now, other users have to recompile the tool to set their own strong name information.

In general, rules could benefit from configurability feature (perhaps storing the configured vaues in the `NuGetPackageVerifier.json` file per rule.

**Comment by joelverhagen** [comment]
Another good candidate for configuration is `AssemblyHasCorrectJsonNetVersionRule`.

**Comment by Eilon** [comment]
@joelverhagen indeed I've been thinking of this as well but never got around to it. DnxTools is open for contributions 😄

**Comment by Eilon** [comment]
BTW in the meantime if it's easier just create a new rule with a specific name for whatever you need. That's Poor Man's Configuration 😄

**Comment by Eilon** [comment]
Closing because there are no plans to do this.
