### ISSUE TITLE
Korebuild update fails on Mac/Linux

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#552]
```
KOREBUILD_TEAMCITY_LOGGER: unbound variable
The command "./build.sh" exited with 1.
```
Running `./run.sh upgrade deps -update` also doesn't seem to help.

cc @ryanbrandenburg @natemcmaster

**Comment by ryanbrandenburg** [comment]
The correct command for right now is `./run.sh upgrade -Update deps` as per aspnet/BuildTools#449.

**Comment by ryanbrandenburg** [comment]
Since the failure is fixed by an update and the inability to update is already covered by #449 I'm closing this.

**Comment by natemcmaster** [comment]
> KOREBUILD_TEAMCITY_LOGGER: unbound variable

@ajaybhargavb what version of korebuild are you using? You probably need a new version. I reverted the change that had this variable. https://github.com/aspnet/BuildTools/commit/5463694d65067bbae2b1b5e2ee070e1539eeb26c
