### ISSUE TITLE
NuGetPackageVerifier: BuildItemsRule doesn't account for framework compatibility

### ISSUE THREAD

**Issue by bricelam** [aspnet/BuildTools#554]
On a package targeting `netstandard2.0`, I want to add an MSBuild item for `netcoreapp2.0`. I get this error:

> BUILD_ITEMS_FRAMEWORK: 'Microsoft.EntityFrameworkCore.Design' contains an MSBuild item for .NETCoreApp,Version=v2.0 even though the package does not define a dependency group for this framework.

There should be no error since the `netcoreapp2.0` build items can be used with the `netstandard2.0` dependency group.

**Comment by natemcmaster** [comment]
_Triage team:_ closing this as low priority.
