### ISSUE TITLE
Add HasRuntimeOutput to all test projects

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#555]
As done [here](https://github.com/aspnet/WebSockets/commit/ec442c3d80ea1ab800350cc401dfebf54291d19e) and suggested [here](https://github.com/aspnet/Home/issues/2813#issuecomment-359895880)

**Comment by natemcmaster** [comment]
I'd rather submit a PR to fix Microsoft.NET.Test.Sdk, so we can fix this for the whole world, not just us. https://github.com/Microsoft/vstest/issues/792

**Comment by Eilon** [comment]
We can just apply it as needed.
