### ISSUE TITLE
`upgrade deps` should preserve line endings

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#556]
Executing `.\build.cmd upgrade deps` on a Windows system will leave build/dependencies.props with mixed line endings. That'll either confuse Git or prompt the user to edit the file and clean the line endings up.

(Fortunately, `.\build.cmd -update ...` doesn't seem to cause mixed line endings in korebuild-lock.txt)

**Comment by natemcmaster** [comment]
Does this happen even after a file is normalized? We're not manipulating line-endings manually. We're using Microsoft.Build.Construction to modify the project file which don't provide API for controlling line endings.

**Comment by dougbu** [comment]
I don't know the behaviour if the file starts with uniform Unix line endings. But, if the file starts with uniform Windows line endings, the edited lines end up with Unix line endings and the untouched lines keep their Windows line endings.

Might be a bug in Microsoft.Build.Construction. Maybe we should use something else? Or, rebuild the entire file? Or, perhaps we should change .gitattributes for *.props files (or only dependencies.props) to give them Unix line endings everywhere -- ugh.

**Comment by Eilon** [comment]
From triage: Justification: the API we use to modify the file doesn’t expose the raw XML document. Implementing this would require a complete rewrite of upgrade-deps.
