### ISSUE TITLE
Update SDK version to get "GetNativeManifest" fix

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#562]
The version of the SDK we currently have is plagued by Microsoft/msbuild#2922. Once there's an SDK which has that fix we should take it so we can start building BuildTools again.

We also need to re-enable the "Update BuildTools" step of Update Universe.

CC @natemcmaster

**Comment by natemcmaster** [comment]
cc @rynowak the latest SDK you need for the Razor SDK work contains this bug Microsoft/msbuild#2922, which blocks us from building other packages in Universe.

**Comment by rynowak** [comment]
Cool beans

**Comment by natemcmaster** [comment]
😢 we need to take a few other changes to build tools. I'm going to revert us back to 2.2.0-preview1-008003 which doesn't have this issue: Microsoft/msbuild#2922

**Comment by rynowak** [comment]
Keep me posted because that SDK doesn't have the changes I need.

**Comment by natemcmaster** [comment]
MSBuild has a PR proposed to fix their bug: https://github.com/Microsoft/msbuild/pull/2923 - assuming this goes in, we should have an SDK soon-ish that we can use.

If not, we will have to workaround in any project that uses ProjectReference/ReferenceOutputAssembly=false
