### ISSUE TITLE
Update LangVersion to 7.2

### ISSUE THREAD

**Issue by anurse** [aspnet/BuildTools#566]
We should move to the latest LangVersion. VS currently supports it, but VSCode does not yet (Omnisharp does, but there hasn't been a release of the C# extension with the updated Omnisharp yet). Once VSCode supports it, we should update.

**Comment by natemcmaster** [comment]
Is there an omnisharp bug to track this?

**Comment by anurse** [comment]
I couldn't find one. Was planning to link it here, but didn't find anything after a few searches of omnisharp/omnisharp-roslyn and omnisharp/omnisharp-vscode

**Comment by natemcmaster** [comment]
vscode supports this now. They release C# 1.14.0 today

**Comment by Eilon** [comment]
I can't think of any reason to not use 7.2. I assume it works fully on .NET Core and .NET Framework? Any reason not to update?

**Comment by natemcmaster** [comment]
What does VS RTM support?

**Comment by anurse** [comment]
I believe I tried it earlier and it fully supported 7.2. 7.2 has been announced as "released" so I would be surprised if it depended upon a prerelease of VS.
