### ISSUE TITLE
Need per branch packages for BuildTools

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#59]
We use these tools in other repos and consequently changes to this might break older APIs. We should instead have these be per branch so we can work on dev and release independently.

**Comment by Eilon** [comment]
We'd need two MyGet feeds as well.

**Comment by Eilon** [comment]
@pranavkm @anurse  do we still need this?

**Comment by pranavkm** [comment]
For now, I've been pinning the versions of the tools as I branch. It's a bit of a pain since these versions are all over the place but it gets the job done.

**Comment by Eilon** [comment]
Ok, kicking the can down the road.

**Comment by natemcmaster** [comment]
I think this can be solved by using semver on our tools package versions. Breaking changes to tasks, targets, or tools should require a version bump to ensure old versions of build system still work.

**Comment by Eilon** [comment]
Closing - pinning is really the solution here because we don't want old branches to ever pick up new build tools, unless we explicitly do so.
