### ISSUE TITLE
Update bootstrap scripts to reflect github TLS requirements

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#593]
Now that GitHub required TLS 1.2 powershell calls to `Invoke-WebRequest` fail by default (because it uses TLS 1.0). We should update our bootstrap scripts to do `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` (or some other way of forcing 1.2) in order to make them work out of the box.

**Comment by Tratcher** [comment]
Note this is primarily needed for the servicing branches. Dev no longer downloads tools from github, it gets them from blob storage.

**Comment by Tratcher** [comment]
Alternatively, update the servicing branches to pull from blob storage.

**Comment by natemcmaster** [comment]
It's only need for 1.x servicing branches which download https://github.com/aspnet/korebuild

**Comment by Eilon** [comment]
Looks like this is already done where needed: https://github.com/aspnet/Identity/commit/82137727992d94fa787388446206acb1f3f54565

If other repos need it and don't have it for servicing 1.0/1.1, we'll add the line then.
