### ISSUE TITLE
Korebuild docs should be more discoverable

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#608]
@ryanbrandenburg just showed me https://github.com/aspnet/BuildTools/blob/dev/docs/KoreBuild.md exists here which I did not know about. Discussed with @ryanbrandenburg and we think it would be more discoverable if this is linked from individual repos.

**Comment by Eilon** [comment]
Let's add a blurb like this: https://github.com/aspnet/Mvc/blob/f0788926a0bbcb0d7afa19918563eb39db7e3c23/README.md#building-from-source

To every repo's README.md at the bottom.

And then from https://github.com/aspnet/Home/wiki let's link to https://github.com/aspnet/BuildTools/blob/dev/docs/KoreBuild.md
