### ISSUE TITLE
Use built-in SDK features for commit hash attributes  and source-link

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#618]
MSBuild and Microsoft.NET.Sdk will soon have the ability to embed commit hashes and other source info. Once that is available, we can probably drop our own implementations of commit hash attribute generation, source link generation and others.

Currently a WIP - cref https://github.com/NuGet/NuGet.Client/pull/2081, https://github.com/Microsoft/msbuild/pull/3063, https://github.com/tmat/repository-info/blob/master/docs/Readme.md by @tmat.

**Comment by natemcmaster** [comment]
https://github.com/dotnet/designs/blob/master/accepted/build/standard-ci-env-variables.md

**Comment by dougbu** [comment]
You mentioned aspnet/AspNetCore#7504 was _part_ of this issue. What remains?

**Comment by natemcmaster** [comment]
Delete obsolete code. :)
