### ISSUE TITLE
Undeclared artifacts exist

### ISSUE THREAD

**Issue by JamesNK** [aspnet/BuildTools#631]
This error on build - when old files are in the artifacts directory - is annoying.

Could part of build be clearing the artifacts directory so you start with a blank slate.

**Comment by jkotalik** [comment]
I run into this everytime I switch between release/2.1 and dev when we branch for a preview (ex one branch is using preview1 and the other is on preview2).

**Comment by natemcmaster** [comment]
Clearing the artifacts directory means we can never make our builds incremental, which is something i was hoping to do in mq. I'd suggest we make it a warning or just drop the error altogether.

**Comment by JamesNK** [comment]
How about making it a warning by default, and in scenarios where you really care about unexpected items, treat the warnings as errors?

**Comment by Eilon** [comment]
We should make it a warning by default unless it's running on the CI, in which case it should be an error.

**Comment by natemcmaster** [comment]
Done. It's a warning for local builds, an error on CI.
