### ISSUE TITLE
Analyzer for test quality

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#633]
It would be nice if we could have an analyzer to catch common testing pitfalls. The one that comes to my mind is `Assert.True(something)` without an explanatory message.

Without more things/more severe things to catch this is probably a Backlog or nights and weekends item, but I'll keep thinking about it to see if there's other items that could be added which would provide more value.

**Comment by Eilon** [comment]
I think xUnit.NET has its own analyzers already. Not sure if it would flag `Assert.True` because sometimes that is the best assertion to use.

**Comment by ryanbrandenburg** [comment]
I'm not anti-`Assert.True` in general (although I do think it's a bit overused), I'm anti-"Assert.True without the message parameter which explains why the build failed". The line numbers you get off the exception stack are not always reliable, so sometimes it's not clear which Assert.True failed, and thus where we should investigate.

**Comment by Eilon** [comment]
Might make sense to get in touch with the xUnit.NET folks to see if it would make sense to have an additional analyzer built in.

**Comment by ryanbrandenburg** [comment]
I've come up with no additional suggestions, so I'm closing this.
