### ISSUE TITLE
Microbenchmark verification only runs for the last project in benchmarks directory

### ISSUE THREAD

**Issue by pakrym** [aspnet/BuildTools#634]

**Comment by Eilon** [comment]
@pakrym - who should look at this?

**Comment by pakrym** [comment]
I will.

**Comment by pakrym** [comment]
Not required for 2.1, it's just our internal validation mechanism to make sure microbenchmarks are not broken by product changes.

**Comment by Eilon** [comment]
OK parking in 2.2.0-mq then.
