### ISSUE TITLE
[Watson] internal.aspnetcore.sdk package is causing project load failures to evaluation expressions errors

### ISSUE THREAD

**Issue by davkean** [aspnet/BuildTools#640]
I do not have a repro, only telemetry, internal.aspnetcore.sdk is causing project load failures with the following:

```
The expression "[MSBuild]::NormalizeDirectory('')" cannot be evaluated. Parameter "path" cannot have zero length. C:\Users\[UserName]\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview1-15626\build\Git.targets
```

This saw hits from December last year right up to end of last month.

**Comment by natemcmaster** [comment]
Where can I go to see this in telemetry? We have something like 700 csproj files that might have hit this, and I would need more details.

**Comment by natemcmaster** [comment]
Closing. Not enough details, and so far, no complaints of issues from our devs.

**Comment by davkean** [comment]
Can you point me to the targets? Devs might not be complaining but the telemetry doesn't lie. We have no other information other than above.

**Comment by natemcmaster** [comment]
https://github.com/aspnet/BuildTools/blob/2af0e2e3d02329b4f0290061ab9bd8c7ca1aa26f/src/Internal.AspNetCore.Sdk/build/Git.targets#L28

**Comment by davkean** [comment]
It looks like the line above it protects against $(RepositoryRoot) being empty.

**Comment by natemcmaster** [comment]
I'll add another condition to be defensive. We find that some people use our build scripts and tools. All of the aspnet org repos have RepositoryRoot set, but if this telemetry can come from outside msft, it's possible it was coming from some other project.

**Comment by davkean** [comment]
It's both internal + external.
