### ISSUE TITLE
Running upgrade deps from release/2.1 branch updates the dependencies.props versions to 2.2.0-*

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/BuildTools#647]
I tried this in Scaffolding repo. I assume it's the same case everywhere.

**Comment by natemcmaster** [comment]
Can be solved by adding this to update every repo.props file.

```diff
   <PropertyGroup>
     <!-- These properties are use by the automation that updates dependencies.props -->
     <LineupPackageId>Internal.AspNetCore.Universe.Lineup</LineupPackageId>
     <LineupPackageRestoreSource>https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json</LineupPackageRestoreSource>

+    <LineupPackageVersion>2.1.0-*</LineupPackageVersion>
   </PropertyGroup>
```

**Comment by natemcmaster** [comment]
Sadly, this won't work for patches after 2.1.0 RTMs. I don't think there is a way to express `2.1.*-*` in NuGet wildcards.

**Comment by ajaybhargavb** [comment]
It already has it but doesn't seem to work. https://github.com/aspnet/Scaffolding/blob/release/2.1/build/repo.props#L7

**Comment by natemcmaster** [comment]
Ah, the version is `2.1.0-rc1-*`. Until 40 minutes ago, there was no build matching this pattern on myget. I think we should change this to `2.1.0-*` now that dev has bumped to 2.2.

**Comment by natemcmaster** [comment]
Try again. It should pull https://dotnet.myget.org/feed/aspnetcore-dev/package/nuget/Internal.AspNetCore.Universe.Lineup/2.1.0-rc1-30592 now.

**Comment by natemcmaster** [comment]
I believe this should be resolved now.
