### ISSUE TITLE
Update the SDK via maestro

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#658]
Reduce the manual effort required to update to known good versions of the SDK.

We already have some scripts in place for this, such as https://github.com/aspnet/BuildTools/blob/dev/scripts/UpdateDependencyVersions.ps1

**Comment by ryanbrandenburg** [comment]
I know that previously we didn't have a source of truth on what SDK builds were "blessed", do we have this now? If so where is it, if not is there a work item somewhere to generate it?

**Comment by natemcmaster** [comment]
Source of truth should be in https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli

**Comment by natemcmaster** [comment]
Closing as wontfix. This feature is being implemented in dotnet/arcade and Maestro.
