### ISSUE TITLE
error : Unable to resolve 'Microsoft.DotNet.GlobalTools.Sdk (>= 2.2.0-preview1-17051)' for '.NETStandard,Version=v0.0'

### ISSUE THREAD

**Issue by smitpatel** [aspnet/BuildTools#674]
A lot of PR builds are failing with above error across different OSs. There was also community issue raised about it here https://github.com/aspnet/EntityFrameworkCore/issues/11988

This is making dotnet bot builds flaky and less reliable.

https://ci3.dot.net/job/aspnet_EntityFrameworkCore/job/dev/job/windows-Configuration_Release_prtest/337/console

**Comment by natemcmaster** [comment]
Potential fix merged into EF https://github.com/aspnet/EntityFrameworkCore/pull/12029. This fix needs to be applied to other repos as well.

Since this is flaky behavior, let's wait a few days to see if this EF change actually resolves the issue.

**Comment by natemcmaster** [comment]
@seancpeters did you see https://github.com/aspnet/Scaffolding/pull/802?

**Comment by seancpeters** [comment]
Nate's fix has fixed my issue.
