### ISSUE TITLE
Need support for getting the SDK version number

### ISSUE THREAD

**Issue by Tratcher** [aspnet/BuildTools#679]
When enabling x86 testing we needed to install the x86 SDK for some repos. Installing the SDK is not that hard, but getting the right version to install takes some work.

ServerTests, MusicStore, and AzureIntegration each need this. The current workaround looks like this:
`<_SdkVersion Condition="'$(_SdkVersion)' == ''">$([System.IO.Path]::GetFileName($([System.IO.Path]::GetDirectoryName('$(MSBuildExtensionsPath)'))))</_SdkVersion>`
See https://github.com/aspnet/ServerTests/pull/123

**Comment by Tratcher** [comment]
For ServerTests and Music store we ended up taking a different approach that did not require the SDK.

**Comment by natemcmaster** [comment]
Ok. Let's close for now, especially given that we want to move the SDK version out of KoreBuild altogether. (cc @ryanbrandenburg and #661 )
