### ISSUE TITLE
VSTS upgrade deps failing

### ISSUE THREAD

**Issue by shhsu** [aspnet/BuildTools#685]
I have a vsts task that invokes
`run.ps1 -d C:\.dotnet -Path $pwd.Path upgrade deps`
It fails on this error
```
Invoke-KoreBuildCommand : You cannot call a method on a null-valued expression.
At E:\A\_work\13\s\run.ps1:204 char:5
+     Invoke-KoreBuildCommand $Command @Arguments
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-KoreBuildCommand], 
    RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Invoke-KoreBuildCommand
```

Both powershell 1.* and 2.* results in the same issue. However, I cannot repo the issue at all outside vsts. I RDP'd into the agent that reports the error and run the exact same command. It runs successfully.

P.S.
1. `Invoke-KoreBuildCommand` exists, `Command` is `upgrade`, `arguments` is `deps`
2. Prior to running `run.ps1 upgrade deps` I ran `run.ps1 install-tools`, that command ran fine.

**Comment by natemcmaster** [comment]
Can you share more details about how you've configured your VSTS task? For example, how did you set `$pwd`?

**Comment by shhsu** [comment]
Btw, my korebuild lock is as followed

```
version:2.2.0-preview1-17066
commithash:a6d45803fb02635f5968ca03bd3325ea6aed8a98
```

Yes, I expect to get $pwd from the environment. In fact, the task right before this one was
`run.ps1 -d C:\.dotnet -Path $pwd.Path -verbose install-tools`
So at this point I am ruling out $pwd not being there because that task ran fine.

Maybe the NPE comes from within `Invoke-KoreBuildCommand $Command @Arguments` beause `command` and `arguments` are both non-null. Is there anyway to enable more diagnostics. Because this error is impossible to repo when I run it outside of VSTS workflow.

**Comment by natemcmaster** [comment]
Try adding `-Debug` to `run.ps1`. I'm not optimistic this will provide much more info. This is a weird error, not sure what would case it.

Also, you're version of KoreBuild is fairly recent, but how new is the `run.ps1` file? Try grabbing the latest bootstrapper scripts from this folder: https://github.com/aspnet/BuildTools/tree/dev/scripts/bootstrapper

**Comment by shhsu** [comment]
More info:

The vsts task is the `Powershell` task. Version `1.*` though I also tried `2.*` and didn't get any different result.
```
Type: File Path
File: run.ps1
Arguments: -d C:\.dotnet -Path $pwd.Path -verbose install-tools
```
The run.ps1 is the latest

Also, as suspected the `-debug` flag didn't give any more trace

**Comment by shhsu** [comment]
I added this method in run.ps1
```
function TestArgs(
    [Parameter(Mandatory = $true)]
    [string]$Command,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Arguments
) {
    Write-Host "Tested: $Command"
    Write-Host "Tested: $Arguments"
}
```
And call it right before `Invoke-KoreBuildCommand`

```
    TestArgs $Command @Arguments
    Invoke-KoreBuildCommand $Command @Arguments
```

`TestArgs` run fine. The NPE is definitely coming from within `Invoke-KoreBuildCommand`

**Comment by shhsu** [comment]
Is there a trivial diagnostic code in KoreBuild and have my `run.ps1` pull that script instead?

**Comment by shhsu** [comment]
I worked around the issue by adding these lines in `run.ps1` `Get-KoreBuild` method before it returns
```
    $dotnetExeHome = Join-Path $DotNetHome "x64"
    $env:PATH = "$dotnetExeHome;$env:PATH"
```

**Comment by shhsu** [comment]
I am a bit hesitant to open this issue because my workaround works currently, but the problem wouldn't be fix by the PR.

Let me clarify. I call `install-tools` in `upgrade deps` in two different VSTS tasks. By the time `upgrade deps` is called, `PATH` is already messed up again because VSTS run each powershell task in an isolated environment. And `$global:dotnet = (Get-Command 'dotnet').Path` actually resolved to `E:\current_dir\dotnet` because dotnet is again not in the path.

So the correct behavior is that after `Get-KoreBuild` is called, PATH is ensured to point to whatever dotnet that this method think it is.

**Comment by natemcmaster** [comment]
Feel free to send a PR.

**Comment by shhsu** [comment]
Will do.

I will read into the code a bit more and determine how korebuild determine the bitness of the dotnet.exe to be used

**Comment by shhsu** [comment]
After the second look the problem. It is actually more subtle then I first described, and it is ultimately VSTS issue.

VSTS actually does generate a `dotnet.exe` and in a temp location, i.e.: `E:\A\bin\dotnet.exe` and forcefully point the PATH to it. Calling `E:\A\bin\dotnet.exe --version" returns empty string and causes an NPE again.

By this line
https://github.com/aspnet/BuildTools/blob/dev/files/KoreBuild/scripts/KoreBuild.psm1#L8
I assume KoreBuild's behavior is to respect PATH and use whatever `dotnet.exe` environment variable tells it to use, and it is a reasonable behavior.
