### ISSUE TITLE
Generate ApiCheck baselines on the fly

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#694]
Currently in order to ensure that we don't remove or modify public API's between releases we generate and check in "baselines" which represent the state of our public API at release. Updating these baselines each time requires us to touch each repo, and the baseline files have a tendency to change a lot and be hard to reason about.

Proposal:
Lets stop using checked in baselines as a source of truth and instead use the nupkg's of our actual releases off of NuGet.

Steps:
1. Find the closest version of a package which is smaller than the current version. (2.1.1 if we're on the 2.2.0 branch).
2. Download that package.
3. Reflect over this package to generate our API data.
4. Compare the data we generated in 3 to the newer package and error for any problems. (Already done)

Pros:
- Our "source of truth" is guaranteed to accurately reflect what a user updating will deal with. Previously we've had difficulty with some packages getting missed in the update, the data we generate being wrong etc. If we generate our "baseline" on the fly based of the actual shipped nupkg then any problems with the generated data can be fixed by updating the ApiCheck tool, and will not also require a re-seed of the data in all repos.
- Less boilerplate in repos. Our current baselines files represent data about a previous state of code, not the current, so they don't really "belong".
- No more churn between releases. We've had a lot of trouble getting `baselines.*.json` files to generate consistently. The ordering has a tendency to be off, and seemingly minor changes can make git diffing algorithms lose the thread and be difficult to review.
- We start getting new baselines instantly upon release rather than waiting for someone to remember that we need to update them, then however long it takes to do.

Cons:
- We take a build-time dependency on previous versions. This means more data to download and a networking point of failure which is not 100% necessary to the build. This is somewhat mitigated by local caches of packages and the ability to turn off ApiCheck temporarily by passing build parameters.
- Likely to be slower. Reflecting over a downloaded DLL is almost certainly going to be slower than just reading json. My bet would be this this difference would be small, but it's a guess.
- Edge cases might be more difficult to deal with. If we rename a package, but still want to keep API compat we would have to have some way of describing their relationship.

Notes:
- We would still need to have `breakingchanges.*.json` or something similar in any offending project, but if your project didn't break anything there will be nothing.

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
