### ISSUE TITLE
build casing issues with assemblies.

### ISSUE THREAD

**Issue by HaoK** [aspnet/BuildTools#697]
It looks like occasionally dlls are renamed with slightly different lowercased names by build.cmd which was causing strange failures in MVC.Testing style functional tests that rely on finding assemblies using Ordinal.

An example:

```
 Directory of C:\Github\AuthSamples\samples\Options.MultiTenant\bin\Debug\netcoreapp2.2

06/21/2018  12:09 PM            16,384 Options.MultiTenant.dll
06/21/2018  12:09 PM            73,216 Options.MultiTenant.Views.dll
               2 File(s)         89,600 bytes

 Directory of C:\Github\AuthSamples\samples\Options.MultiTenant\obj\Debug\netcoreapp2.2

06/21/2018  12:09 PM            16,384 Options.MultiTenant.dll
06/21/2018  12:09 PM            73,216 Options.Multitenant.Views.dll
```

Notice how the obj/Debug/netcoreapp2.2 has lowercase Mutlitenant.Views.dll

cc @natemcmaster @ryanbrandenburg @javiercn

**Comment by ryanbrandenburg** [comment]
It looks like package you're referring to is [here](https://github.com/aspnet/AuthSamples/tree/haok/options/samples/Options.MultiTenant)?

**Comment by HaoK** [comment]
Yep that's the branch with the PR that has a repro. I'm going to merge this once CI passes on the updated PR.

**Comment by HaoK** [comment]
PR: https://github.com/aspnet/AuthSamples/pull/44

**Comment by natemcmaster** [comment]
@pranavkm @rynowak is this a known issue in the Razor compiler?

@HaoK I don't think this is the result of tools in KoreBuild. It looks like a product bug in Microsoft.NET.Sdk.Razor.

**Comment by pranavkm** [comment]
> is this a known issue in the Razor compiler?

Nope, first I've come across this. The file name's produced from [`$(TargetName)`](https://github.com/aspnet/Razor/blob/dev/src/Microsoft.NET.Sdk.Razor/build/netstandard2.0/Sdk.Razor.CurrentVersion.targets#L123) - it should be the same casing for the two. Did you happen to rename the file between builds?

**Comment by HaoK** [comment]
No manual stuff was done @pranavkm 

This is what's produced after a git clean xdf + build.cmd

**Comment by HaoK** [comment]
Its resulting in the mvc funtional tests failing due to casing, its weird because the local fix with casing worked on my laptop, but its not working on CI: https://ci.appveyor.com/project/aspnetci/authsamples/build/1.0.122

**Comment by pranavkm** [comment]
Looks like those test are failing due to an incorrect path: 

```
 System.ArgumentException : The content root 'C:\projects\authsamples\Options.Multitenant' does not exist.
  Parameter name: contentRoot
```

**Comment by HaoK** [comment]
Yup, @javiercn and I debugged this last week, this is failing due to the casing:

 https://github.com/aspnet/Mvc/blame/dev/src/Microsoft.AspNetCore.Mvc.Testing/WebApplicationFactory.cs#L208

**Comment by natemcmaster** [comment]
Closing as this doesn't appear to be a problem anymore.
