### ISSUE TITLE
Auto-resolve the most common merge conflicts

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#707]
Let's see if we can update scripts/GitHubMergeBranches.ps1 to handle this better.

![image](https://user-images.githubusercontent.com/2696087/42487889-e99e7384-83b7-11e8-90b7-fe6d5a834f29.png)

cc @pranavkm @pakrym

**Comment by natemcmaster** [comment]
Just throwing out ideas. What if we let users specify a merge strategy per file/globbing pattern via korebuild.json? Most repos could have something like this:

```js
{
  "mergeStrategies": {
    "korebuild-lock.txt": "Ours",
    "build/dependencies.props": { "name": "XmlDepsMerge", "options": "HighestVersion" },
    "submodules/*/": "Ours"
  }
}
```

Something like this would be great in aspnet/Universe which always has a bunch of merge conflicts.

**Comment by pranavkm** [comment]
That seems nice. For the deps file, do we actually want to merge, rather than take `ours` and for the master branch UpdateRepos to update it?

**Comment by natemcmaster** [comment]
Yeah, the deps file needs a special merge because it's not uncommon to add/delete version variables as dependencies shift.

**Comment by pakrym** [comment]
`.\run merge-stuff` that would detect if there are conflicts in deps/lock/other special files and fix merges for them. The bot can run it and commit the result or a person can do it too.

**Comment by natemcmaster** [comment]
I think we should have the tool take in [standard git mergetool arguments](https://stackoverflow.com/a/20382333/2526265) such as $BASE $LOCAL $REMOTE $MERGED. Then you should be able to run `git mergetool --tool=korebuild` and it will do its magic

**Comment by natemcmaster** [comment]
we don't already have a merge tool. I'm currently thinking that if we do, we might as well implement it in arcade so it can be easily used by everyone.

**Comment by natemcmaster** [comment]
Putting this in the backlog as low priority for now.

**Comment by pranavkm** [comment]
Close? We don't have this issue any longer.

**Comment by natemcmaster** [comment]
Yeah, we're not going to spend time on this one. We shouldn't have to deal with many merge conflicts now that we've finished condensing repos.
