### ISSUE TITLE
Update our SDK to 2.1.400

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#710]
Be good comrades and upgrade our build tools to 2.1.400. There are some features we can take advantage of:

* global shim generation for global tools
* DOTNET_CLI_HOME (cc @wli3 @peterhuene - any docs on this? We have been using DOTNET_HOME in our scripts for a few years, and wonder if DOTNET_CLI_HOME is now a first-class thing that behaves the same)
* some new built-in MSBuild tasks, like Zip, Unzip, DownloadFile, GetFileHash, etc

**Comment by peterhuene** [comment]
DOTNET_CLI_HOME instructs the CLI and NuGet where to create the `.dotnet` and `.nuget` directories, respectively.  Its purpose is to set an alternative HOME for the dotnet cli that only affects dotnet and NuGet; primarily for CI scenarios that run with users without a HOME directory.

There are currently no docs for it afaik.

**Comment by natemcmaster** [comment]
Does Visual Studio (i.e. MSBuildSdkResolver, NuGet restore) honor DOTNET_CLI_HOME?

One of the problems we have, and have to constantly work around, is that we need aspnet build scripts to install .NET Core into a user-writable location, like %HOME%/.dotnet, but VS installers put %ProgramFiles%/dotnet on PATH first. It means our contributors frequently have to modify PATH so that Visual Studio will prefer %HOME%/.dotnet first. Would be awesome if we could just have our contributors set DOTNET_CLI_HOME to %HOME% and then VS just started working.

**Comment by peterhuene** [comment]
Only the .NET Core SDK and NuGet (built for .NET Core) use it, so a restore done by Visual Studio I'm guessing will not.  `DOTNET_CLI_HOME` is expected to point at a directory where you would like the files written by the .NET Core SDK (sentinel files used during the first-run experience, global tools, user nuget cache, etc).

I think MSBuildSdkResolver respects `DOTNET_MSBUILD_SDK_RESOLVER_CLI_DIR` to point at a directory containing the muxer, but it's primarily used for tests afaik.

**Comment by ryanbrandenburg** [comment]
@natemcmaster should we leave this issue open to track the work of taking advantage of some of this new hotness?

**Comment by natemcmaster** [comment]
Yes. There is more work to be done. I merged the update to 2.1.400 just to see if we run into any problems compiling with the newer SDK. Once that goes through, we can move forward with replacing our tools with in-box stuff.

**Comment by natemcmaster** [comment]
Had to revert. aspnetcore can build with 2.1.302 and fails with 2.1.400.

I had time to add one workaround: https://github.com/aspnet/Universe/pull/1322, but 2.2 builds are still failing with the new SDK.

The next error I'm hitting:

> C:\b\w\1973e9914e89f587\.dotnet\x64\sdk\2.1.400\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error NETSDK1005: Assets file 'C:\b\w\1973e9914e89f587\modules\IISIntegration\src\Microsoft.AspNetCore.Server.IIS\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project.

https://github.com/aspnet/IISIntegration/blob/release/2.2/src/Microsoft.AspNetCore.Server.IIS/Microsoft.AspNetCore.Server.IIS.csproj

I'll try to create a repro tomorrow and open an issue.

**Comment by natemcmaster** [comment]
https://github.com/Microsoft/msbuild/issues/3626

**Comment by natemcmaster** [comment]
Other changes are required to react to web.config generation changes: https://github.com/aspnet/IISIntegration/pull/1249

**Comment by natemcmaster** [comment]
This was finished up a few weeks ago.
