### ISSUE TITLE
Remove Designer.cs files from source control, generate on the fly

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#728]
Part of incremental changes to move to arcade. dotnet/arcade#88

Arcade has a task for generating the Designer.cs files for .resx  strings at build time. This works much better than our command-line targets for resx generation. Let's convert to arcade's approach for this instead.

**Comment by dougbu** [comment]
@natemcmaster I doubt this is actually "small" because so much of our code uses the `Format...` methods and not the properties in our `Designer.cs` files.

One alternative to changing a large swath of our code that @tmat mentioned yesterday: Enhance the Arcade tool so that it supports these methods as well. Do we have an issue open requesting such an enhancement? (I couldn't find more than comments about different `.resx` handling.)

**Comment by natemcmaster** [comment]
Yes, adopting the way Arcade generates the C# API would be prohibitively expensive right now. I would still like to investigate generating on the fly. I think we could probably add a setting to arcade's code gen (https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GenerateResxSource.cs) which produces the format we've been using 
 (see https://github.com/aspnet/BuildTools/blob/master/modules/BuildTools.Tasks/GenerateResxDesignerFiles.cs).

I talked about this yesterday with Mark, too, and he said he would be okay adding an 'aspnetcore-flavor' resx generator into aspnetcore. 

FWIW - I made a prototype of this last week, borrowing from the approach Arcade uses, and it seemed to work well in aspnet/Extensions: https://github.com/natemcmaster/AspNetBuildTools/tree/resx/src/Internal.AspNetCore.ResxTools

**Comment by tmat** [comment]
Can we avoid having a different tool? I'd prefer having a switch in the Arcade resx generator that produces the methods you need. We already did something similar for CoreFX.

**Comment by dougbu** [comment]
> We already did something similar for CoreFX.

CoreFX uses `Format...` methods?

In any case, I agree it would be good to use a single tool and, if possible, a single format. The fact (say) four repos use the added methods and the rest initially do not won't be a big deal. Ideal if we don't need even a new switch here.

**Comment by natemcmaster** [comment]
Example difference:

Arcade:
```c#
    internal static partial class Resources
    {
        private static global::System.Resources.ResourceManager s_resourceManager;
        internal static global::System.Resources.ResourceManager ResourceManager => s_resourceManager ?? (s_resourceManager = new global::System.Resources.ResourceManager(typeof(Resources)));
        internal static global::System.Globalization.CultureInfo Culture { get; set; }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        internal static string GetResourceString(string resourceKey, string defaultValue = null) =>  ResourceManager.GetString(resourceKey, Culture);
        /// <summary>Cannot create instance of type '{0}' because it is either abstract or an interface.</summary>
        internal static string Error_CannotActivateAbstractOrInterface => GetResourceString("Error_CannotActivateAbstractOrInterface");
        /// <summary>Failed to convert '{0}' to type '{1}'.</summary>
        internal static string Error_FailedBinding => GetResourceString("Error_FailedBinding");
        /// <summary>Failed to create instance of type '{0}'.</summary>
        internal static string Error_FailedToActivate => GetResourceString("Error_FailedToActivate");
        /// <summary>Cannot create instance of type '{0}' because it is missing a public parameterless constructor.</summary>
        internal static string Error_MissingParameterlessConstructor => GetResourceString("Error_MissingParameterlessConstructor");
        /// <summary>Cannot create instance of type '{0}' because multidimensional arrays are not supported.</summary>
        internal static string Error_UnsupportedMultidimensionalArray => GetResourceString("Error_UnsupportedMultidimensionalArray");

    }
```

AspNetCore
```c#

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.Extensions.Configuration.Binder.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// Cannot create instance of type '{0}' because it is either abstract or an interface.
        /// </summary>
        internal static string Error_CannotActivateAbstractOrInterface
        {
            get => GetString("Error_CannotActivateAbstractOrInterface");
        }

        /// <summary>
        /// Cannot create instance of type '{0}' because it is either abstract or an interface.
        /// </summary>
        internal static string FormatError_CannotActivateAbstractOrInterface(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("Error_CannotActivateAbstractOrInterface"), p0);

        /// <summary>
        /// Failed to convert '{0}' to type '{1}'.
        /// </summary>
        internal static string Error_FailedBinding
        {
            get => GetString("Error_FailedBinding");
        }

        /// <summary>
        /// Failed to convert '{0}' to type '{1}'.
        /// </summary>
        internal static string FormatError_FailedBinding(object p0, object p1)
            => string.Format(CultureInfo.CurrentCulture, GetString("Error_FailedBinding"), p0, p1);

        /// <summary>
        /// Failed to create instance of type '{0}'.
        /// </summary>
        internal static string Error_FailedToActivate
        {
            get => GetString("Error_FailedToActivate");
        }

        /// <summary>
        /// Failed to create instance of type '{0}'.
        /// </summary>
        internal static string FormatError_FailedToActivate(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("Error_FailedToActivate"), p0);

        /// <summary>
        /// Cannot create instance of type '{0}' because it is missing a public parameterless constructor.
        /// </summary>
        internal static string Error_MissingParameterlessConstructor
        {
            get => GetString("Error_MissingParameterlessConstructor");
        }

        /// <summary>
        /// Cannot create instance of type '{0}' because it is missing a public parameterless constructor.
        /// </summary>
        internal static string FormatError_MissingParameterlessConstructor(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("Error_MissingParameterlessConstructor"), p0);

        /// <summary>
        /// Cannot create instance of type '{0}' because multidimensional arrays are not supported.
        /// </summary>
        internal static string Error_UnsupportedMultidimensionalArray
        {
            get => GetString("Error_UnsupportedMultidimensionalArray");
        }

        /// <summary>
        /// Cannot create instance of type '{0}' because multidimensional arrays are not supported.
        /// </summary>
        internal static string FormatError_UnsupportedMultidimensionalArray(object p0)
            => string.Format(CultureInfo.CurrentCulture, GetString("Error_UnsupportedMultidimensionalArray"), p0);

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
```

**Comment by natemcmaster** [comment]
My search results in VS Code show about at least 851 usages of the `Resources.Format...` methods in our code base.

**Comment by natemcmaster** [comment]
Also, does the Arcade generator support named placeholders, not just numbered ones?

E.g.:
```xml
  <data name="Antiforgery_RequiresSSL" xml:space="preserve">
    <value>The antiforgery system has the configuration value {optionName} = {value}, but the current request is not an SSL request.</value>
  </data>
```

**Comment by dougbu** [comment]
How much do we use the named parameters?

**Comment by dougbu** [comment]
> Example difference:

Main thing that doesn't look like an implementation difference is the _addition_ of the `Format...` methods. Did I miss anything?

**Comment by natemcmaster** [comment]
> How much do we use the named parameters?

111 strings have this.

This was done so the string could be passed directly to `ILogger` which supports turning named placeholders into structured log data.

**Comment by tmat** [comment]
This is the Arcade implementation:
https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GenerateResxSource.cs

For CoreFX @ericstj added `AsConstants` https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/src/GenerateResxSource.cs#L51

We can generalize a bit and add `MemberKind : string = "Constant" | "Property" | "Method"`

**Comment by dougbu** [comment]
> We can generalize a bit and add `MemberKind : string = "Constant" | "Property" | "Method"`

Constants and properties really are either / or. But, methods seem separate e.g. from @natemcmaster's example `Error_CannotActivateAbstractOrInterface` _and_ `FormatError_CannotActivateAbstractOrInterface(object p0)`. (AspNetCore has hit some places where the methods can't be used.)

But, why not generate the methods unconditionally?

**Comment by tmat** [comment]
So you sometimes use properties and sometimes methods? That seems odd.

Because they are not used by most repos and they would clutter completion list. Each project should decide on a convention and follow it consistently imo. Ideally we would be able to unify across all repos but that would indeed be a lot of work, so I'm fine with a parameter that determines the convention.

**Comment by tmat** [comment]
If you need both properties and methods then adding `GenerateMethods` bool would also work.

**Comment by ericstj** [comment]
Rather than doing as constants I'd recommend just using "nameof(Property)".   The asconstants switch was mainly a stop-gap when I was porting desktop code that I didn't want to churn a lot.

> why not generate the methods unconditionally?

Interesting proposal.  Unconditionally might cause bloat since not all strings are formattable.  The code generator could do this whenever it saw a format specifier in the resource string.  It could even omit the property in those cases to avoid people forgetting to pass in values for the parameters.

**Comment by ericstj** [comment]
For reference, here's how CoreFx solves the formatting problem (adding method to the partial class): 
https://github.com/dotnet/corefx/search?q=SR.Format&unscoped_q=SR.Format
https://github.com/dotnet/corefx/blob/8c5260061b11323dfd97fbab614d54402405513f/src/Common/src/System/SR.cs#L41-L84

It's not pretty but it works with minimal duplication (in our case we name the resources class SR to further minimize the duplication in sources).
