### ISSUE TITLE
Check in the global.json file, use this to control SDK versions

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#729]
Part of incremental changes to move to arcade. dotnet/arcade#88

@ryanbrandenburg prototyped checking in the global.json file instead of generating it on the fly. (#661). Let's finish up this implementation and switch to using it to match what Arcade does.

**Comment by dougbu** [comment]
@natemcmaster `global.json` is checked into all four of our repos, at least in our `master` branches. And, those files specify the SDK.

What work remains here?

**Comment by natemcmaster** [comment]
Two changes needed to complete this:

1. Update Korebuild to read global.json to find the .NET Core SDK version it should install
2. Decouple KoreBuild from the version of the .NET Core SDK (harder than it sounds)

At this point, only the aspnet/AspNetCore repo is using KoreBuild, so I would be fine if we didn't do this. Seems like a low priority.

**Comment by natemcmaster** [comment]
At this point, I think this investment is not worth it. We only have one repo left using KoreBuild, and we plan to move it to Arcade soon.

Closing as 'wontfix'.
