### ISSUE TITLE
VSTS Templates: Publish Build Artifacts even on failed build

### ISSUE THREAD

**Issue by anurse** [aspnet/BuildTools#736]
This is extremely useful for diagnosing failed tests/builds that drop logs into the artifacts directory. Right now the template only publishes for successful builds:

https://github.com/aspnet/BuildTools/blob/af4b785bfec5b5e5b7a2d74971bed0d372d1b37d/.vsts-pipelines/templates/phases/default-build.yml#L94-L96

**Comment by natemcmaster** [comment]
Something to think about: https://github.com/Microsoft/msbuild/issues/3603

**Comment by anurse** [comment]
Agreed, which is why I definitely understand not turning on binary logs by default :)

**Comment by natemcmaster** [comment]
Resolved in https://github.com/aspnet/BuildTools/pull/741
