### ISSUE TITLE
Internal.AspNetCore.Sdk overwrites core NuSpec attributes even when already specified

### ISSUE THREAD

**Issue by anurse** [aspnet/BuildTools#737]
I'm using Internal.AspNetCore.Sdk in SignalR/SignalR to get source link and some other features but I need the License Url, Project Url, etc. to be different. I set them in the Directory.Build.props but then the SDK comes along and whacks them :(.

The properties set here should be done only if the value isn't already set: 

https://github.com/aspnet/BuildTools/blob/af4b785bfec5b5e5b7a2d74971bed0d372d1b37d/src/Internal.AspNetCore.Sdk/build/Common.props#L12-L29

**Comment by natemcmaster** [comment]
#738 looks like the only feasible fix for this since D.B.props is imported before NuGet imports.

**Comment by anurse** [comment]
It's generally good MSBuild hygene to use that pattern where possible anyway :)
