### ISSUE TITLE
Add a java requirement to korebuild.schema

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#745]
Let's add a definable requirement for Java like we have for [node](https://github.com/aspnet/BuildTools/blob/master/tools/korebuild.schema.json#L40) and VS. This would be useful in repos like aspnet/Templating and aspnet/Blazor where we use Java to run selenium.

**Comment by ryanbrandenburg** [comment]
Seems like a waste since we're trying to leave KoreBuild? @natemcmaster  and @mkArtakMSFT, any reason not to just close this?

**Comment by natemcmaster** [comment]
Agreed. Let's close it.
