### ISSUE TITLE
Test console output is packed with successful test run information

### ISSUE THREAD

**Issue by anurse** [aspnet/BuildTools#749]
There are huge amounts of text in the build logs from our test runs that is completely irrelevant because it's just the test log output of successful tests.

As far as I can tell this is because vstest or xunit dumps `ITestOutputHelper` content to stdout when the `--diag` switch is provided to `dotnet vstest`. We should consider:

* Removing the `--diag` switch (we'd lose the useful diag logs on every build, though I don't have context on how often those have been useful)
* Getting `vstest` or `xunit` (whomever is responsible) to provide an option to disable this output even in diag most
* Pipe `dotnet vstest` stdout to a file for each invocation rather than letting them spam the build's stdout.

Also related to the huge amount of log data: https://github.com/aspnet/EntityFrameworkCore/issues/13211

**Comment by natemcmaster** [comment]
I don't know if there is a good default. @mkArtakMSFT asked yesterday about how to add _more_ console output to tests.

**Comment by anurse** [comment]
More output from successful tests? That seems kinda absurd to me.

Right now, we know at least 50% of the console output is skipped test notification: https://github.com/aspnet/EntityFrameworkCore/issues/13211 - That's completely unnecessary and causes a significant delay in trying to identify the cause of a build failure.

Looking at the output from a recent Ubuntu-Universe test run, there are tons of lines of test logs from **successful tests** which are irrelevant when looking for a build failure.

I'm curious what the `--diag` logs have helped us resolve in the past. A lot of this seems to be related to having that switch present. VSTest seems to not only dump logs to those files but dump a **massive** amount more logging information to the *console*, which is very disruptive.

**Comment by natemcmaster** [comment]
Are you talking about lines at look like this?

> [04:13:46]i:		 [VSTest] Microsoft.EntityFrameworkCore.Cosmos.Sql.Query.SimpleQueryCosmosSqlTest.Microsoft.EntityFrameworkCore.Cosmos.Sql.Query.SimpleQueryCosmosSqlTest.Join_customers_orders_projection(isAsync: False)

If so, that is TeamCity doing the logging, not vstest or korebuild. I haven't found a way to disable this logging.

**Comment by anurse** [comment]
That's one of many kinds of output I'm talking about yes. Also included:

Skipped Tests (~40,000 lines):
```
EntityFrameworkCore   |   [xUnit.net 00:00:06.68]     Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Navigation_accessed_twice_outside_and_inside_subquery(isAsync: True) [SKIP]

...

EntityFrameworkCore   |   Skipped  Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Navigation_accessed_twice_outside_and_inside_subquery(isAsync: True

[04:16:39]i:			 [Microsoft.EntityFrameworkCore.Query.SpatialQuerySqlServerTest.Microsoft.EntityFrameworkCore.Query.SpatialQuerySqlServerTest.Union(isAsync: True)] [Test Output]
Unmet assembly test condition(s): LocalDb is not accessible on this platform. An external SQL Server must be configured.
```

ITestOutputHelper output from successful tests in Kestrel, SignalR, Identity (example below is a *single* test):
```
... 3,516 lines removed ...
| [1.722s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGJ3RAGVSDR" paused.
| [1.723s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGJ3RAGVSDR" resumed.
| [1.723s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGJ3RAGVSDR" paused.
| [1.723s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGJ3RAGVSDR" resumed.
| [1.723s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGJ3RAGVSDR", Request id "0HLGJ3RAGVSDR:00000001": done reading request body.
| [1.724s] Microsoft.AspNetCore.Hosting.Internal.WebHost Information: Request finished in 1676.13ms 200 
| [1.724s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGJ3RAGVSDR" disconnecting.
| [1.724s] Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets Debug: Connection id "0HLGJ3RAGVSDR" sending FIN.
| [1.725s] Microsoft.AspNetCore.Server.Kestrel Debug: Connection id "0HLGJ3RAGVSDR" stopped.
| [1.725s] Microsoft.AspNetCore.Hosting.Internal.WebHost Debug: Hosting shutdown
| [1.744s] TestLifetime Information: Finished test LargeUpload-16384-False-True in 1.7411325s
```

The last one is one of the largest blocks. We log a lot of content to Xunit's `ITestOutputHelper`, which is great when a test fails. RaaS gives us a blob of content in the issue that includes the failure and all the logs for the test. This is extremely valuable content. However, when `--diag` is provided to `dotnet vstest`, we also get all this content written to stdout.

**Comment by natemcmaster** [comment]
Let's start by turning off `--diag` in TeamCity.

Let's also look into:
* piping vstest to a file
* scraping the file for test failure information and printing to stdout so it shows up in main build output

**Comment by natemcmaster** [comment]
Closing. As a part of migrating our repos to use Arcade, we're now using their defaults for test runners. All test output from the test runners are piped into log files in the artifacts/ folder. This reduces console output quite a bit. It also has some downsides, like making it harder to see failures, but that piece of feedback is something for the Arcade team to consider and address. https://github.com/dotnet/arcade/issues/2142
