### ISSUE TITLE
PR against dotnet/cli to make dotnet-install scripts match

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/BuildTools#752]
As discussed [here](https://github.com/aspnet/BuildTools/pull/750#issuecomment-418903684).

**Comment by ryanbrandenburg** [comment]
These changes weren't effective on Linux/Mac, the work item here should now be to remove our changes from BuildTools when we're not in the middle of a release.

**Comment by ryanbrandenburg** [comment]
Actually @mkArtakMSFT shouldn't we push this to early 3.0.0-preview1 if we want to avoid destabilizing a release? It's entirely a build-time change anyway.

**Comment by natemcmaster** [comment]
Closing. This isn't important enough
