### ISSUE TITLE
`Sdk_GenerateResxDesignerFiles` task applied to all resources

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#765]
For projects that contain non-`*.resx` resources, `dotnet msbuild /t:resx` spits out incorrect warnings e.g.
```
...\packages\internal.aspnetcore.sdk\2.2.0-preview1-20180821.1\build\Common.targets(59,5): warning :
'ManifestResourceName' was not set on ServiceProjectReferenceMetadata.targets. [...\src\Microsoft.Extensions.ApiDescription.Client\Microsoft.Extensions.ApiDescription.Client.csproj]
```

One reason this happens is the `Sdk_GenerateResxDesignerFiles` task is applied to all embedded resources. Another reason is the task checks for `ManifestResourceName` before it checks an item's `Type`. Probably simpler to fix the second reason i.e. reverse those checks.

**Comment by natemcmaster** [comment]
Closing in favor of https://github.com/aspnet/BuildTools/issues/728.
