### ISSUE TITLE
ApiCheck: Members relocated higher up in the hierarchy tree should not be marked as breaking changes

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/BuildTools#767]
See https://github.com/aspnet/KestrelHttpServer/pull/2959#discussion_r221002524.

If a method from a subclass is moved to a base class, it should not be considered a breaking change. We should update the API check tool to recognize such scenarios.

**Comment by natemcmaster** [comment]
FYI - https://github.com/aspnet/BuildTools/issues/747 we're not really working on API check tool anymore.

**Comment by JunTaoLuo** [comment]
Oh I see.
