### ISSUE TITLE
NuGetPackageVerifier should support wildcards 

### ISSUE THREAD

**Issue by dougbu** [aspnet/BuildTools#776]
I just had to add ~1500 lines to NuGetPackageVerifier.json in the MVC repo for a single package. Most of these lines would be handled with a few simple wildcards e.g. `"tools/net461/System.*.dll": "Packing Publish output and therefore including CoreFx assemblies"`.

Even better would be an ability to mark package paths (with wildcards 😀) as e.g. `Framework` and disable a number of rules in one shot. For example, that might disable specific signing key and version requirements.

**Comment by Eilon** [comment]
@dougbu I don't see the change in MVC. Can you point to the commit/PR?

**Comment by dougbu** [comment]
My commit is still local because other things about it are busted. I'm working on a aspnet/Mvc#8428 fix.

**Comment by Eilon** [comment]
Can you share some more info on what the 1500 lines are? Why do we need to re-package hundreds of .NET Core product assemblies in our own package?

**Comment by natemcmaster** [comment]
I'm wary of wildcards as a solution here. We generally like the strictness around which assemblies end up in our packages because it forces us to know what is in our NuGet packages.

**Comment by dougbu** [comment]
> Why do we need to re-package hundreds of .NET Core product assemblies in our own package?

Most of our tools either have an inside man with no unique dependencies e.g. `dotnet-ef` or have no inside man at all e.g. `dotnet-dev-certs`. However the client code generator package contains a tool with an inside man that requires `TestHost` and `TestHost` is usually not referenced from an ASP.NET Core web site project.

> I'm wary of wildcards as a solution here. 

I'm taking about `Microsoft.AspNetCore.*.dll`, `Microsoft.Extensions.*.dll` and (for .NET 4.6.1 cases) `System.*.dll`, not wider and blinder wildcards. And, we should be able to narrow things down after more testing with a variety of web projects.
