### ISSUE TITLE
SignTool fails in VSTS and Jenkins, but not TeamCity

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#787]
Reported by @jkotalik , @smitpatel  and others. Something about SignTool fails in VSTS and Jenkins PR validation builds. It doesn't fail in TeamCity, which is why the bot keeps trying to update repos to the latest version of BuildTools.

> signtool : error : D:\j\workspace\windows-Confi---dfc477d1\artifacts\build\Microsoft.AspNetCore.Server.IISIntegration.2.2.0-preview3-906.nupkg has part lib/netstandard2.0/Microsoft.AspNetCore.Server.IISIntegration.dll which does not match the content in the binaries directory

I suspect it is related to incorrect project configurations which leads to double builds of binaries.

**Comment by ryanbrandenburg** [comment]
Related issue [here](https://github.com/aspnet/AspNetCore-Internal/issues/1131).

**Comment by pakrym** [comment]
Happens in feature build in TeamCity too: http://aspnetci/viewLog.html?buildId=572666&buildTypeId=Lite_IISIntegration&tab=buildLog&_focus=1129

**Comment by natemcmaster** [comment]
Assigning to myself to investigate.

**Comment by natemcmaster** [comment]
I investigated further. It appears that signtool is doing the right thing, but adding the tool causes the build to fail because IISIntegration is doing a double build of all projects. The custom target `/t:PackageStressTestApp` re-builds the graph of its dependencies. This causes a mismatch between the version of Microsoft.AspNetCore.Server.IISIntegration.dll in the .nupkg and on disk.

This should be resolved with https://github.com/aspnet/IISIntegration/pull/1483.

Closing as so far I have not found changes required in BuildTools.

**Comment by smitpatel** [comment]
> 12:41:59 signtool : error : D:\j\workspace\windows-Confi---21b17462\artifacts\build\dotnet-ef.2.2.0-preview3-368.nupkg has part tools/netcoreapp2.2/any/dotnet-ef.dll which does not match the content in the binaries directory [C:\Users\dotnet-bot\.dotnet\buildtools\korebuild\2.2.0-preview2-20181001.5\KoreBuild.proj]

https://ci3.dot.net/job/aspnet_EntityFrameworkCore/job/release_2.2/job/windows-Configuration_Release_prtest/368/console

There are many PRs which failed like that.

**Comment by natemcmaster** [comment]
Can you point to PRs which have KoreBuild >= 2.2.0-preview2-20181003.2? A fix went into buildtools a week ago which fixed a common source of double writes: https://github.com/aspnet/BuildTools/pull/778

The PR you linked to is using a version of KoreBuild affected by the bug: 2.2.0-preview2-20181001.5

**Comment by smitpatel** [comment]
https://ci3.dot.net/job/aspnet_EntityFrameworkCore/job/release_2.2/job/windows-Configuration_Release_prtest/422/console

> 16:53:20 signtool : error : D:\j\workspace\windows-Confi---21b17462\artifacts\build\dotnet-ef.2.2.0-preview3-422.nupkg has part tools/netcoreapp2.2/any/dotnet-ef.dll which does not match the content in the binaries directory [C:\Users\dotnet-bot\.dotnet\buildtools\korebuild\2.2.0-preview2-20181004.6\KoreBuild.proj]

**Comment by natemcmaster** [comment]
Any chance you can capture binary logs?

**Comment by smitpatel** [comment]
I am not sure how to capture binary logs. Repro is not so consistent but creating any PR has good probability of getting failure. Can you submit a PR on EF Core repo with code to capture logs?

**Comment by natemcmaster** [comment]
No changes necessary to build tools. EF's target dependencies causes a double build of dotnet-ef.dll. Should be fixed with https://github.com/aspnet/EntityFrameworkCore/pull/13597
