### ISSUE TITLE
Using a response file to improve DependenciesPackager's performance

### ISSUE THREAD

**Issue by troydai** [aspnet/BuildTools#96]
Suggested by @javiercn in PR #95 

> I would suggest that if you are performing this overhaul of the tool, you try and follow an alternative approach for doing crossgen that consists on passing the semi colon separated list of paths to the tool instead of copying everything to a folder and running crossgen. 
> This will have a noticeable improvement in performance for the tool and if the size of the command line becomes a problem, you can write a response file in the following format
> /nologo
> /App_Paths path1;path2;....
> And then call crossgen with crossgen.exe /in PathToin.dll /out /PathToOuthDll @response.rsp
> This will avoid copying all the files to an intermediate folder which takes like 20% of the tools time if not more.
> What I'm suggesting is, get all the dependencies from the project context, build a rsp file with /App_Paths < and pass that to the crossgen input with @myresponsefile.rsp instead of copying the assemblies to a staging folder

**Comment by Eilon** [comment]
@javiercn is this still useful?

**Comment by javiercn** [comment]
@Eilon Yes, plus I can do it as part of the "refactor" that I need to do for adding "extra things" to our cache

**Comment by Eilon** [comment]
Ok, please do the needful.

**Comment by javiercn** [comment]
This is done as part of 6da936c9b816fff743355db82dd3cb28e110f901
