### ISSUE TITLE
[aspnet-build] Run NuGetPackageVerifier during build.cmd/build.sh

### ISSUE THREAD

**Issue by anurse** [aspnet/BuildTools#99]
It's really easy to mess something up when adding projects, and probably better to put this verification in the inner loop since it's pretty fast.

**Comment by pranavkm** [comment]
From https://github.com/aspnet/Common/pull/153#issuecomment-250019033,

* Make NPV run on *every* dev build with all rules that will generally pass on local dev machines
* Remove the default list of packages; make sure that the default composite rule set that is used has the right rules
* Have the CI run all the rules that aren't runnable on dev builds

**Comment by Eilon** [comment]
@ajaybhargavb I thought maybe we already do this? Or not?

**Comment by pranavkm** [comment]
Yeah, this one's done.

**Comment by ajaybhargavb** [comment]
Yes, this can be closed.

**Comment by Eilon** [comment]
Ok.
